Program lngcv;

   { LNG-CV VERSION 1.0.1 / THE MIT LICENSE (MIT) © 2022 PIOTR BAJDEK }

Uses
   Crt, SysUtils;

Var
   INPUT1, INPUT2, INPUT3: String;
   STR1, STR2, STR3, STR4, STR5, STR6, STR7, STR8, STR9, STR10, STR11, STR12, STR13, STR14, STR15, STR16, STR17, STR18, STR19, STR20, STR21, STR22, STR23, STR24, STR25, STR26, STR27, STR28, STR29, STR30, STR31, STR32, STR33, STR34, STR35, STR36, STR37, STR38, STR39, STR40, STR41, STR42, STR43, STR44, STR45, STR46, STR47, STR48, STR49, STR50, STR51, STR52, STR53, STR54, STR55, STR56, STR57, STR58, STR59, STR60, STR61, STR62, STR63, STR64, STR65, STR66, STR67, STR68, STR69, STR70, STR71, STR72, STR73, STR74, STR75, STR76, STR77, STR78, STR79, STR80, STR81, STR82, STR83, STR84, STR85, STR86, STR87, STR88, STR89, STR90, STR91, STR92, STR93, STR94, STR95, STR96, STR97, STR98, STR99, STR100, STR101, STR102, STR103, STR104, STR105, STR106, STR107, STR108, STR109, STR110, STR111, STR112, STR113, STR114, STR115, STR116, STR117, STR118, STR119, STR120, STR121, STR122, STR123, STR124, STR125, STR126, STR127, STR128, STR129, STR130, STR131, STR132, STR133, STR134, STR135, STR136, STR137, STR138, STR139, STR140, STR141, STR142, STR143, STR144, STR145, STR146, STR147, STR148, STR149, STR150, STR151, STR152, STR153, STR154, STR155, STR156, STR157, STR158, STR159, STR160: String;

Label
   HELP;

Begin

   INPUT1 := ParamStr(1);
   INPUT2 := ParamStr(2);
   INPUT3 := ParamStr(3);

   { ABOUT }

   If INPUT1 = '--about' Then
   Begin
      Writeln('Program:  lng-cv');
      Writeln('Version:  1.0.1');
      Writeln('Date:     February 01, 2022');
      Writeln('Author:   Piotr Bajdek, Poland');
      Writeln('Contact:  piotr.bajdek@protonmail.com');
      Writeln('Source:   https://github.com/piotrbajdek/lng-cv');
      Writeln('License:  The MIT License (MIT) © 2022 Piotr Bajdek');
      Halt;
   End;

   { NO ARGUMENTS }

   If INPUT1 = '' Then
   Begin
      GoTo HELP;
   End;

   { HELP }

   If INPUT1 = '--help' Then
   HELP:
   Begin
      TextColor(15);
      Writeln('Usage:    lng-cv [OPTION_1] [OPTION_2] [STRING]');
      Writeln('');
      TextColor(7);
      Writeln('OPTION_1:');
      Writeln('          --ipa  Transcribe [STRING] into the International Phonetic Alphabet');   
      Writeln('          --ort  Convert [STRING] between regional norms of orthography');
      Writeln('');
      Writeln('OPTION_2:');
      Writeln('          --eng  English | option available for:        --ort');
      Writeln('          --lat  Latin   | option available for: --ipa, --ort');
      Writeln('          --qwe  Quechua | option available for:        --ort');     
      Writeln('          --tca  Tikuna  | option available for: --ipa, --ort');
      Writeln('');
      TextColor(15);
      Writeln('Example:  lng-cv --ipa --lat "Vēnī, vīdī, vīcī."');
      Writeln('');
      TextColor(7);
      Writeln('          Note: For multi-word queries always use quotation marks!');
      Writeln('                At present, the output cannot exceed 256 bytes.');
      Writeln('');
      Writeln('Other options:');
      Writeln('                 --about     Show contact and program info');
      Writeln('                 --help      Show this help');
      Writeln('                 --license   Show licesing information');
      Writeln('                 --version   Show the program version');
      Writeln('');
      TextColor(15);
      Writeln('English:');
      TextColor(7);
      Writeln('          In the --ort mode, the text is transcribed into American English.');
      Writeln('');
      TextColor(15);
      Writeln('Latin:');
      TextColor(7);
      Writeln('          The modern spelling of Latin and the ancient convention can be used');
      Writeln('          indifferently in the --ipa mode. To mark the duration of vowels,');
      Writeln('          type either apices or macrons. In the --ort mode, the text is');
      Writeln('          transcribed into the ancient convention (before the 2nd c. AC).');
      Writeln('');
      TextColor(15);
      Writeln('Quechua:');
      TextColor(7);
      Writeln('          In the --ort mode, it is possible to transcribe some text between');
      Writeln('          the trivocalic and the pentavocalic orthographic conventions.');
      Writeln('');
      TextColor(15);
      Writeln('Tikuna:');
      TextColor(7);
      Writeln('          Two variants of pronunciation (Nazareth, CO; Umariaçu, BR) (--ipa)');
      Writeln('          and four distinct orthographic conventions (--ort) are supported.');
      Writeln('          There is no support for tones at this stage of program development,');
      Writeln('          as it would require building a large dialectal dictionary. Even so,');
      Writeln('          in the IPA mode tonal letters can be displayed if inserted manually');
      Writeln('          as numbers beginning from 1 (the lowest) to 5 (the highest tone).');
      Halt
   End;

   { LICENSE }

   If INPUT1 = '--license' Then
   Begin
      Writeln('The MIT License (MIT)');
      Writeln('');
      Writeln('Copyright © 2022 Piotr Bajdek');
      Writeln('');
      Writeln('Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:');
      Writeln('');
      Writeln('The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.');
      Writeln('');
      Writeln('THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.');
      Halt;
   End;

   { VERSION }

   If INPUT1 = '--version' Then
   Begin
      Writeln('Version: 1.0.1');
      Writeln('February 01, 2022');
      Halt;
   End;

   { INTERNATIONAL PHONETIC ALPHABET }

   If INPUT1 = '--ipa' Then
   Begin

   { NO LANGUAGE SELECTED  }

      If INPUT2 ='' Then
      Begin
         TextColor(4);
         Writeln('Error:    No language selected! Add: [OPTION_2]');
         Writeln('');
         GoTo HELP;
      End;

   { IPA: LATIN }

      If INPUT2 = '--lat' Then
      Begin
   { EMPTY LATIN STRING }
         If INPUT3 = '' Then
         Begin
            TextColor(4);
            Writeln('Error:    No string inserted! Add: [STRING]');
            Writeln('');
            GoTo HELP;
         End;

         STR1 := INPUT3;
         STR2 := StringReplace(STR1, 'A', 'a', [rfReplaceAll]);
         STR3 := StringReplace(STR2, 'Ā', 'ā', [rfReplaceAll]);
         STR4 := StringReplace(STR3, 'Á', 'ā', [rfReplaceAll]);
         STR5 := StringReplace(STR4, 'B', 'b', [rfReplaceAll]);
         STR6 := StringReplace(STR5, 'bs', 'ps', [rfReplaceAll]);
         STR7 := StringReplace(STR6, 'bt', 'pt', [rfReplaceAll]);
         STR8 := StringReplace(STR7, 'C', 'c', [rfReplaceAll]);
         STR9 := StringReplace(STR8, 'D', 'd', [rfReplaceAll]);
         STR10 := StringReplace(STR9, 'E', 'e', [rfReplaceAll]);
         STR11 := StringReplace(STR10, 'Ē', 'ē', [rfReplaceAll]);
         STR12 := StringReplace(STR11, 'É', 'ē', [rfReplaceAll]);
         STR13 := StringReplace(STR12, 'Ë', 'ë', [rfReplaceAll]);
         STR14 := StringReplace(STR13, 'F', 'f', [rfReplaceAll]);
         STR15 := StringReplace(STR14, 'G', 'ɡ', [rfReplaceAll]);
         STR16 := StringReplace(STR15, 'g', 'ɡ', [rfReplaceAll]);
         STR17 := StringReplace(STR16, 'H', 'h', [rfReplaceAll]);
         STR18 := StringReplace(STR17, 'I', 'i', [rfReplaceAll]);
         STR19 := StringReplace(STR18, 'Ī', 'ī', [rfReplaceAll]);
         STR20 := StringReplace(STR19, 'Í', 'ī', [rfReplaceAll]);
         STR21 := StringReplace(STR20, 'ꟾ', 'ī', [rfReplaceAll]);
         STR22 := StringReplace(STR21, 'J', 'j', [rfReplaceAll]);
         STR23 := StringReplace(STR22, 'K', 'k', [rfReplaceAll]);
         STR24 := StringReplace(STR23, 'L', 'l', [rfReplaceAll]);
         STR25 := StringReplace(STR24, 'M', 'm', [rfReplaceAll]);
         STR26 := StringReplace(STR25, 'N', 'n', [rfReplaceAll]);
         STR27 := StringReplace(STR26, 'O', 'o', [rfReplaceAll]);
         STR28 := StringReplace(STR27, 'Ō', 'ō', [rfReplaceAll]);
         STR29 := StringReplace(STR28, 'Ó', 'ō', [rfReplaceAll]);
         STR30 := StringReplace(STR29, 'P', 'p', [rfReplaceAll]);
         STR31 := StringReplace(STR30, 'Q', 'q', [rfReplaceAll]);
         STR32 := StringReplace(STR31, 'R', 'r', [rfReplaceAll]);
         STR33 := StringReplace(STR32, 'S', 's', [rfReplaceAll]);
         STR34 := StringReplace(STR33, 'T', 't', [rfReplaceAll]);
         STR35 := StringReplace(STR34, 'V', 'u', [rfReplaceAll]);
         STR36 := StringReplace(STR35, 'v', 'u', [rfReplaceAll]);
         STR37 := StringReplace(STR36, 'uu', 'vu', [rfReplaceAll]);
         STR38 := StringReplace(STR37, 'ui', 'vi', [rfReplaceAll]);
         STR39 := StringReplace(STR38, 'ue', 've', [rfReplaceAll]);
         STR40 := StringReplace(STR39, 'ua', 'va', [rfReplaceAll]);
         STR41 := StringReplace(STR40, 'uo', 'vo', [rfReplaceAll]);
         STR42 := StringReplace(STR41, 'uũ', 'vũ', [rfReplaceAll]);
         STR43 := StringReplace(STR42, 'uī', 'vī', [rfReplaceAll]);
         STR44 := StringReplace(STR43, 'uē', 'vē', [rfReplaceAll]);
         STR45 := StringReplace(STR44, 'uā', 'vā', [rfReplaceAll]);
         STR46 := StringReplace(STR45, 'uō', 'vō', [rfReplaceAll]);
         STR47 := StringReplace(STR46, 'U', 'u', [rfReplaceAll]);
         STR48 := StringReplace(STR47, 'Ū', 'ū', [rfReplaceAll]);
         STR49 := StringReplace(STR48, 'Ú', 'ū', [rfReplaceAll]);
         STR50 := StringReplace(STR49, 'Ü', 'ü', [rfReplaceAll]);
         STR51 := StringReplace(STR50, 'W', 'w', [rfReplaceAll]);
         STR52 := StringReplace(STR51, 'X', 'x', [rfReplaceAll]);
         STR53 := StringReplace(STR52, 'Y', 'y', [rfReplaceAll]);
         STR54 := StringReplace(STR53, 'Ȳ', 'ȳ', [rfReplaceAll]);
         STR55 := StringReplace(STR54, 'Ý', 'ý', [rfReplaceAll]);
         STR56 := StringReplace(STR55, 'Z', 'z', [rfReplaceAll]);
         STR57 := StringReplace(STR56, 'Ă', 'ă', [rfReplaceAll]);
         STR58 := StringReplace(STR57, 'Ĕ', 'ĕ', [rfReplaceAll]);
         STR59 := StringReplace(STR58, 'Ĭ', 'ĭ', [rfReplaceAll]);
         STR60 := StringReplace(STR59, 'Ŏ', 'ŏ', [rfReplaceAll]);
         STR61 := StringReplace(STR60, 'Ŭ', 'ŭ', [rfReplaceAll]);
         STR62 := StringReplace(STR61, 'Y̆', 'y̆', [rfReplaceAll]);
         STR63 := StringReplace(STR62, 's', 's̺', [rfReplaceAll]);
         STR64 := StringReplace(STR63, 's̺b', 's̬b', [rfReplaceAll]);
         STR65 := StringReplace(STR64, 's̺d', 's̬d', [rfReplaceAll]);
         STR66 := StringReplace(STR65, 's̺ɡ', 's̬ɡ', [rfReplaceAll]);
         STR67 := StringReplace(STR66, 's̺m', 's̬m', [rfReplaceAll]);
         STR68 := StringReplace(STR67, 's̺n', 's̬n', [rfReplaceAll]);
         STR69 := StringReplace(STR68, 'nd', 'md', [rfReplaceAll]);
         STR70 := StringReplace(STR69, 'n d', 'm d', [rfReplaceAll]);
         STR71 := StringReplace(STR70, 'np', 'mp', [rfReplaceAll]);
         STR72 := StringReplace(STR71, 'n p', 'm p', [rfReplaceAll]);
         STR73 := StringReplace(STR72, 'nf', 'ɱf', [rfReplaceAll]);
         STR74 := StringReplace(STR73, 'n f', 'ɱ f', [rfReplaceAll]);
         STR75 := StringReplace(STR74, 'nm', 'mm', [rfReplaceAll]);
         STR76 := StringReplace(STR75, 'n m', 'm m', [rfReplaceAll]);
         STR77 := StringReplace(STR76, 'nq', 'ŋq', [rfReplaceAll]);
         STR78 := StringReplace(STR77, 'n q', 'ŋ q', [rfReplaceAll]);
         STR79 := StringReplace(STR78, 'nc', 'ŋc', [rfReplaceAll]);
         STR80 := StringReplace(STR79, 'n c', 'ŋ c', [rfReplaceAll]);
         STR81 := StringReplace(STR80, 'c', 'k', [rfReplaceAll]);
         STR82 := StringReplace(STR81, 'q', 'k', [rfReplaceAll]);
         STR83 := StringReplace(STR82, 'ii', 'jː', [rfReplaceAll]);
         STR84 := StringReplace(STR83, 'l', 'ɫ', [rfReplaceAll]);
         STR85 := StringReplace(STR84, 'ɫɫ', 'll', [rfReplaceAll]);
         STR86 := StringReplace(STR85, 'ɫi', 'li', [rfReplaceAll]);
         STR87 := StringReplace(STR86, 'rh', 'r̥', [rfReplaceAll]);
         STR88 := StringReplace(STR87, 'v', 'w', [rfReplaceAll]);
         STR89 := StringReplace(STR88, 'x', 'k͡s̺', [rfReplaceAll]);
         STR90 := StringReplace(STR89, 'ɡn', 'ŋn', [rfReplaceAll]);
         STR91 := StringReplace(STR90, 'ë', 'ɛ', [rfReplaceAll]);
         STR92 := StringReplace(STR91, 'ü', 'ʊ', [rfReplaceAll]);
         STR93 := StringReplace(STR92, 'ĕr', 'ær', [rfReplaceAll]);
         STR94 := StringReplace(STR93, 'ie', 'īe', [rfReplaceAll]);
         STR95 := StringReplace(STR94, 'cum', 'kʉm', [rfReplaceAll]);
         STR96 := StringReplace(STR95, 'ptim', 'ptɨm', [rfReplaceAll]);
         STR97 := StringReplace(STR96, 'crim', 'krɨm', [rfReplaceAll]);
         STR98 := StringReplace(STR97, 'um ', 'ũː ', [rfReplaceAll]);
         STR99 := StringReplace(STR98, 'um,', 'ũː,', [rfReplaceAll]);
         STR100 := StringReplace(STR99, 'um.', 'ũː.', [rfReplaceAll]);
         STR101 := StringReplace(STR100, 'um?', 'ũː?', [rfReplaceAll]);
         STR102 := StringReplace(STR101, 'um!', 'ũː!', [rfReplaceAll]);
         STR103 := StringReplace(STR102, 'um·', 'ũː·', [rfReplaceAll]);
         STR104 := StringReplace(STR103, 'em ', 'ẽː ', [rfReplaceAll]);
         STR105 := StringReplace(STR104, 'em,', 'ẽː,', [rfReplaceAll]);
         STR106 := StringReplace(STR105, 'em;', 'ẽː;', [rfReplaceAll]);
         STR107 := StringReplace(STR106, 'em.', 'ẽː.', [rfReplaceAll]);
         STR108 := StringReplace(STR107, 'em?', 'ẽː?', [rfReplaceAll]);
         STR109 := StringReplace(STR108, 'em!', 'ẽː!', [rfReplaceAll]);
         STR110 := StringReplace(STR109, 'em·', 'ẽː·', [rfReplaceAll]);
         STR111 := StringReplace(STR110, 'ens', 'ẽːs̺', [rfReplaceAll]);
         STR112 := StringReplace(STR111, 'ons', 'õːs̺', [rfReplaceAll]);
         STR113 := StringReplace(STR112, 'inf', 'ĩːf', [rfReplaceAll]);
         STR114 := StringReplace(STR113, 'ia', 'ja', [rfReplaceAll]);
         STR115 := StringReplace(STR114, 'ii', 'jː', [rfReplaceAll]);
         STR116 := StringReplace(STR115, 'io', 'jo', [rfReplaceAll]);
         STR117 := StringReplace(STR116, 'iu', 'ju', [rfReplaceAll]);
         STR118 := StringReplace(STR117, 'iā', 'jā', [rfReplaceAll]);
         STR119 := StringReplace(STR118, 'iī', 'jː', [rfReplaceAll]);
         STR120 := StringReplace(STR119, 'iō', 'jō', [rfReplaceAll]);
         STR121 := StringReplace(STR120, 'iū', 'jū', [rfReplaceAll]);
         STR122 := StringReplace(STR121, 'ea', 'ia', [rfReplaceAll]);
         STR123 := StringReplace(STR122, 'ae', 'ɐɛ̯', [rfReplaceAll]);
         STR124 := StringReplace(STR123, 'oe', 'ɔɛ̯', [rfReplaceAll]);
         STR125 := StringReplace(STR124, 'i', 'i̞', [rfReplaceAll]);
         STR126 := StringReplace(STR125, 'o', 'ɔ', [rfReplaceAll]);
         STR127 := StringReplace(STR126, 'u', 'ʊ', [rfReplaceAll]);
         STR128 := StringReplace(STR127, 'y', 'ʏ', [rfReplaceAll]);
         STR129 := StringReplace(STR128, 'a', 'ɐ', [rfReplaceAll]);
         STR130 := StringReplace(STR129, 'e', 'ɛ', [rfReplaceAll]);
         STR131 := StringReplace(STR130, 'ā', 'aː', [rfReplaceAll]);
         STR132 := StringReplace(STR131, 'á', 'aː', [rfReplaceAll]);
         STR133 := StringReplace(STR132, 'ē', 'eː', [rfReplaceAll]);
         STR134 := StringReplace(STR133, 'é', 'eː', [rfReplaceAll]);
         STR135 := StringReplace(STR134, 'ī', 'iː', [rfReplaceAll]);
         STR136 := StringReplace(STR135, 'í', 'iː', [rfReplaceAll]);
         STR137 := StringReplace(STR136, 'ō', 'oː', [rfReplaceAll]);
         STR138 := StringReplace(STR137, 'ó', 'oː', [rfReplaceAll]);
         STR139 := StringReplace(STR138, 'ū', 'uː', [rfReplaceAll]);
         STR140 := StringReplace(STR139, 'ú', 'uː', [rfReplaceAll]);
         STR141 := StringReplace(STR140, 'ȳ', 'yː', [rfReplaceAll]);
         STR142 := StringReplace(STR141, 'ý', 'yː', [rfReplaceAll]);
         STR143 := StringReplace(STR142, 'ă', 'ɐ', [rfReplaceAll]);
         STR144 := StringReplace(STR143, 'ĕ', 'ɛ', [rfReplaceAll]);
         STR145 := StringReplace(STR144, 'ĭ', 'i̞', [rfReplaceAll]);
         STR146 := StringReplace(STR145, 'ŏ', 'ɔ', [rfReplaceAll]);
         STR147 := StringReplace(STR146, 'ŭ', 'ʊ', [rfReplaceAll]);
         STR148 := StringReplace(STR147, 'y̆', 'ʏ', [rfReplaceAll]);
         STR149 := StringReplace(STR148, 'er', 'ær', [rfReplaceAll]);
         STR150 := StringReplace(STR149, ',', ' ∣', [rfReplaceAll]);
         STR151 := StringReplace(STR150, ';', ' ∥', [rfReplaceAll]);
         STR152 := StringReplace(STR151, ':', ' ∣', [rfReplaceAll]);
         STR153 := StringReplace(STR152, '.', ' ∥', [rfReplaceAll]);
         STR154 := StringReplace(STR153, '!', ' ∥', [rfReplaceAll]);
         STR155 := StringReplace(STR154, '?', ' ∥', [rfReplaceAll]);
         STR156 := StringReplace(STR155, '(', '∣ ', [rfReplaceAll]);
         STR157 := StringReplace(STR156, ')', ' ∣', [rfReplaceAll]);
         STR158 := StringReplace(STR157, '·', ' ', [rfReplaceAll]);
         STR159 := StringReplace(STR158, ' - ', ' ∣ ', [rfReplaceAll]);
         STR160 := StringReplace(STR159, ' – ', ' ∣ ', [rfReplaceAll]);
         Writeln('');
         Writeln('Classical Latin:');
         Writeln('');
         TextColor(15);
         Writeln('   ',STR156);
         TextColor(7);
         Writeln('');
         Halt;
      End;

   { IPA: TIKUNA }

      If INPUT2 = '--tca' Then
      Begin
   { EMPTY TIKUNA STRING }
         If INPUT3 = '' Then
         Begin
            TextColor(4);
            Writeln('Error:    No string inserted! Add: [STRING]');
            Writeln('');
            GoTo HELP;
         End;
   { IPA: NAZARETH }
         STR1 := INPUT3;
         STR2 := StringReplace(STR1, '1', '˩', [rfReplaceAll]);
         STR3 := StringReplace(STR2, '2', '˨', [rfReplaceAll]);
         STR4 := StringReplace(STR3, '3', '˧', [rfReplaceAll]);
         STR5 := StringReplace(STR4, '4', '˦', [rfReplaceAll]);
         STR6 := StringReplace(STR5, '5', '˥', [rfReplaceAll]);
         STR7 := StringReplace(STR6, 'x', 'ʔ', [rfReplaceAll]);
         STR8 := StringReplace(STR7, 'X', 'ʔ', [rfReplaceAll]);
         STR9 := StringReplace(STR8, '''', 'ʔ', [rfReplaceAll]);
         STR10 := StringReplace(STR9, '’', 'ʔ', [rfReplaceAll]);
         STR11 := StringReplace(STR10, 'B', 'β', [rfReplaceAll]);
         STR12 := StringReplace(STR11, 'CUE', 'kUE', [rfReplaceAll]);
         STR13 := StringReplace(STR12, 'CUI', 'kUI', [rfReplaceAll]);
         STR14 := StringReplace(STR13, 'C', 'k', [rfReplaceAll]);
         STR15 := StringReplace(STR14, 'TkH', 'CH', [rfReplaceAll]);
         STR16 := StringReplace(STR15, 'kH', 'CH', [rfReplaceAll]);
         STR17 := StringReplace(STR16, 'CH', 'ʧ', [rfReplaceAll]);
         STR18 := StringReplace(STR17, 'D', 'd', [rfReplaceAll]);
         STR19 := StringReplace(STR18, 'NG', 'ŋ', [rfReplaceAll]);
         STR20 := StringReplace(STR19, 'G', 'ɡ', [rfReplaceAll]);
         STR21 := StringReplace(STR20, 'M', 'm', [rfReplaceAll]);
         STR22 := StringReplace(STR21, 'N', 'n̪', [rfReplaceAll]);
         STR23 := StringReplace(STR22, 'NH', 'Ñ', [rfReplaceAll]);
         STR24 := StringReplace(STR23, 'Ñ', 'ɲ', [rfReplaceAll]);
         STR25 := StringReplace(STR24, 'P', 'p', [rfReplaceAll]);
         STR26 := StringReplace(STR25, 'QUE', 'kE', [rfReplaceAll]);
         STR27 := StringReplace(STR26, 'QUI', 'kI', [rfReplaceAll]);
         STR28 := StringReplace(STR27, 'Q', 'k', [rfReplaceAll]);
         STR29 := StringReplace(STR28, 'R', 'ɾ', [rfReplaceAll]);
         STR30 := StringReplace(STR29, 'T', 't̪', [rfReplaceAll]);
         STR31 := StringReplace(STR30, 'W', 'ɰ', [rfReplaceAll]);
         STR32 := StringReplace(STR31, 'Y', 'd͡ʒ', [rfReplaceAll]);
         STR33 := StringReplace(STR32, 'J', 'd͡ʒ', [rfReplaceAll]);
         STR34 := StringReplace(STR33, 'F', 'ɸ', [rfReplaceAll]);
         STR35 := StringReplace(STR34, 'L', 'l', [rfReplaceAll]);
         STR36 := StringReplace(STR35, 'Z', 'S', [rfReplaceAll]);
         STR37 := StringReplace(STR36, 'Ç', 'S', [rfReplaceAll]);
         STR38 := StringReplace(STR37, 'S', 's̺', [rfReplaceAll]);
         STR39 := StringReplace(STR38, 'V', 'ɰ', [rfReplaceAll]);
         STR40 := StringReplace(STR39, 'b', 'β', [rfReplaceAll]);
         STR41 := StringReplace(STR40, 'w', 'ɰ', [rfReplaceAll]);
         STR42 := StringReplace(STR41, 'v', 'ɰ', [rfReplaceAll]);
         STR43 := StringReplace(STR42, 'cue', 'kue', [rfReplaceAll]);
         STR44 := StringReplace(STR43, 'Cue', 'kue', [rfReplaceAll]);
         STR45 := StringReplace(STR44, 'cui', 'kui', [rfReplaceAll]);
         STR46 := StringReplace(STR45, 'Cui', 'kui', [rfReplaceAll]);
         STR47 := StringReplace(STR46, 'c', 'k', [rfReplaceAll]);
         STR48 := StringReplace(STR47, 'tkh', 'ch', [rfReplaceAll]);
         STR49 := StringReplace(STR48, 'Tkh', 'ch', [rfReplaceAll]);
         STR50 := StringReplace(STR49, 'kh', 'ch', [rfReplaceAll]);
         STR51 := StringReplace(STR50, 'Kh', 'ch', [rfReplaceAll]);
         STR52 := StringReplace(STR51, 'ch', 'ʧ', [rfReplaceAll]);
         STR53 := StringReplace(STR52, 'd', 'd', [rfReplaceAll]);
         STR54 := StringReplace(STR53, 'Nɡ', 'ŋ', [rfReplaceAll]);
         STR55 := StringReplace(STR54, 'ng', 'ŋ', [rfReplaceAll]);
         STR56 := StringReplace(STR55, 'g', 'ɡ', [rfReplaceAll]);
         STR57 := StringReplace(STR56, 'n', 'n̪', [rfReplaceAll]);
         STR58 := StringReplace(STR57, 'nh', 'ñ', [rfReplaceAll]);
         STR59 := StringReplace(STR58, 'Nh', 'ñ', [rfReplaceAll]);
         STR60 := StringReplace(STR59, 'ñ', 'ɲ', [rfReplaceAll]);
         STR61 := StringReplace(STR60, 'que', 'ke', [rfReplaceAll]);
         STR62 := StringReplace(STR61, 'Que', 'ke', [rfReplaceAll]);
         STR63 := StringReplace(STR62, 'qui', 'ki', [rfReplaceAll]);
         STR64 := StringReplace(STR63, 'Qui', 'ki', [rfReplaceAll]);
         STR65 := StringReplace(STR64, 'q', 'k', [rfReplaceAll]);
         STR66 := StringReplace(STR65, 'r', 'ɾ', [rfReplaceAll]);
         STR67 := StringReplace(STR66, 't', 't̪', [rfReplaceAll]);
         STR68 := StringReplace(STR67, 'y', 'd͡ʒ', [rfReplaceAll]);
         STR69 := StringReplace(STR68, 'j', 'd͡ʒ', [rfReplaceAll]);
         STR70 := StringReplace(STR69, 'f', 'ɸ', [rfReplaceAll]);
         STR71 := StringReplace(STR70, 'z', 's', [rfReplaceAll]);
         STR72 := StringReplace(STR71, 'ç', 's', [rfReplaceAll]);
         STR73 := StringReplace(STR72, 's', 's̺', [rfReplaceAll]);
         STR74 := StringReplace(STR73, 'K', 'k', [rfReplaceAll]);
         STR75 := StringReplace(STR74, 'ã', 'ɐ̱̃', [rfReplaceAll]);
         STR76 := StringReplace(STR75, 'ü̃', 'ɨ̱̃', [rfReplaceAll]);
         STR77 := StringReplace(STR76, 'a̱', 'ʌ̰', [rfReplaceAll]);
         STR78 := StringReplace(STR77, 'e̱', 'ë', [rfReplaceAll]);
         STR79 := StringReplace(STR78, 'i̱', 'ɪ', [rfReplaceAll]);
         STR80 := StringReplace(STR79, 'o̱', 'ö', [rfReplaceAll]);
         STR81 := StringReplace(STR80, 'u̱', 'ṵ', [rfReplaceAll]);
         STR82 := StringReplace(STR81, 'ü̱', 'ɯ̈', [rfReplaceAll]);
         STR83 := StringReplace(STR82, 'á', 'a', [rfReplaceAll]);
         STR84 := StringReplace(STR83, 'é', 'e', [rfReplaceAll]);
         STR85 := StringReplace(STR84, 'í', 'i', [rfReplaceAll]);
         STR86 := StringReplace(STR85, 'ó', 'o', [rfReplaceAll]);
         STR87 := StringReplace(STR86, 'ú', 'ʉ̱', [rfReplaceAll]);
         STR88 := StringReplace(STR87, 'ǘ', 'ü', [rfReplaceAll]);
         STR89 := StringReplace(STR88, 'à', 'a', [rfReplaceAll]);
         STR90 := StringReplace(STR89, 'è', 'e', [rfReplaceAll]);
         STR91 := StringReplace(STR90, 'ì', 'i', [rfReplaceAll]);
         STR92 := StringReplace(STR91, 'ò', 'o̞', [rfReplaceAll]);
         STR93 := StringReplace(STR92, 'ù', 'ʉ̱', [rfReplaceAll]);
         STR94 := StringReplace(STR93, 'ǜ', 'ü', [rfReplaceAll]);
         STR95 := StringReplace(STR94, 'd͡ʒae', 'd͡ʒæː', [rfReplaceAll]);
         STR96 := StringReplace(STR95, 'a', 'ɐ̱', [rfReplaceAll]);
         STR97 := StringReplace(STR96, 'o', 'o', [rfReplaceAll]);
         STR98 := StringReplace(STR97, 'u', 'ʉ̱', [rfReplaceAll]);
         STR99 := StringReplace(STR98, 'ü', 'ɨ̱', [rfReplaceAll]);
         STR100 := StringReplace(STR99, 'Ã', 'ɐ̱̃', [rfReplaceAll]);
         STR101 := StringReplace(STR100, 'Ẽ', 'ẽ', [rfReplaceAll]);
         STR102 := StringReplace(STR101, 'Ĩ', 'ĩ', [rfReplaceAll]);
         STR103 := StringReplace(STR102, 'Õ', 'õ', [rfReplaceAll]);
         STR104 := StringReplace(STR103, 'Ũ', 'ũ', [rfReplaceAll]);
         STR105 := StringReplace(STR104, 'Ü̃', 'ɨ̱̃', [rfReplaceAll]);
         STR106 := StringReplace(STR105, 'A̱', 'ʌ̰', [rfReplaceAll]);
         STR107 := StringReplace(STR106, 'E̱', 'ë', [rfReplaceAll]);
         STR108 := StringReplace(STR107, 'I̱', 'ɪ', [rfReplaceAll]);
         STR109 := StringReplace(STR108, 'O̱', 'ö', [rfReplaceAll]);
         STR110 := StringReplace(STR109, 'U̱', 'ṵ', [rfReplaceAll]);
         STR111 := StringReplace(STR110, 'Ü̱', 'ɯ̈', [rfReplaceAll]);
         STR112 := StringReplace(STR111, 'Á', 'ɐ̱', [rfReplaceAll]);
         STR113 := StringReplace(STR112, 'É', 'e', [rfReplaceAll]);
         STR114 := StringReplace(STR113, 'Í', 'i', [rfReplaceAll]);
         STR115 := StringReplace(STR114, 'Ó', 'o', [rfReplaceAll]);
         STR116 := StringReplace(STR115, 'Ú', 'ʉ̱', [rfReplaceAll]);
         STR117 := StringReplace(STR116, 'Ǘ', 'Ü', [rfReplaceAll]);
         STR118 := StringReplace(STR117, 'À', 'ɐ̱', [rfReplaceAll]);
         STR119 := StringReplace(STR118, 'È', 'e', [rfReplaceAll]);
         STR120 := StringReplace(STR119, 'Ì', 'i', [rfReplaceAll]);
         STR121 := StringReplace(STR120, 'Ò', 'o', [rfReplaceAll]);
         STR122 := StringReplace(STR121, 'Ù', 'ʉ̱', [rfReplaceAll]);
         STR123 := StringReplace(STR122, 'Ǜ', 'Ü', [rfReplaceAll]);
         STR124 := StringReplace(STR123, 'd͡ʒAE', 'd͡ʒæː', [rfReplaceAll]);
         STR125 := StringReplace(STR124, 'A', 'ɐ̱', [rfReplaceAll]);
         STR126 := StringReplace(STR125, 'E', 'e', [rfReplaceAll]);
         STR127 := StringReplace(STR126, 'I', 'i', [rfReplaceAll]);
         STR128 := StringReplace(STR127, 'O', 'o', [rfReplaceAll]);
         STR129 := StringReplace(STR128, 'U', 'ʉ̱', [rfReplaceAll]);
         STR130 := StringReplace(STR129, 'Ü', 'ɨ̱', [rfReplaceAll]);
         STR131 := StringReplace(STR130, 'ʉ̱̰', 'ṵ', [rfReplaceAll]);
         STR132 := StringReplace(STR131, '.', ' ∥', [rfReplaceAll]);
         STR133 := StringReplace(STR132, ',', ' ∣', [rfReplaceAll]);
         STR134 := StringReplace(STR133, ';', ' ∥', [rfReplaceAll]);
         STR135 := StringReplace(STR134, ':', ' ∣', [rfReplaceAll]);
         STR136 := StringReplace(STR135, '?', ' ∥', [rfReplaceAll]);
         STR137 := StringReplace(STR136, '¿', '', [rfReplaceAll]);
         STR138 := StringReplace(STR137, '!', ' ∥', [rfReplaceAll]);
         STR139 := StringReplace(STR138, '¡', '', [rfReplaceAll]);
         STR140 := StringReplace(STR139, ' - ', ' ∣ ', [rfReplaceAll]);
         STR141 := StringReplace(STR140, ' – ', ' ∣ ', [rfReplaceAll]);
         STR142 := StringReplace(STR141, '(', '∣ ', [rfReplaceAll]);
         STR143 := StringReplace(STR142, ')', ' ∣', [rfReplaceAll]);
         STR144 := StringReplace(STR143, 'n̪̪ɡ', 'ŋ', [rfReplaceAll]);
         Writeln('');
         TextColor(7);
         Writeln('Central Tikuna (Nazareth, Colombia):');
         Writeln('');
         TextColor(15);
         Writeln('   ',STR144);
   { IPA: UMARIAÇU }
         STR1 := INPUT3;
         STR2 := StringReplace(STR1, '1', '˩', [rfReplaceAll]);
         STR3 := StringReplace(STR2, '2', '˨', [rfReplaceAll]);
         STR4 := StringReplace(STR3, '3', '˧', [rfReplaceAll]);
         STR5 := StringReplace(STR4, '4', '˦', [rfReplaceAll]);
         STR6 := StringReplace(STR5, '5', '˥', [rfReplaceAll]);
         STR7 := StringReplace(STR6, 'x', 'ʔ', [rfReplaceAll]);
         STR8 := StringReplace(STR7, 'X', 'ʔ', [rfReplaceAll]);
         STR9 := StringReplace(STR8, '''', 'ʔ', [rfReplaceAll]);
         STR10 := StringReplace(STR9, '’', 'ʔ', [rfReplaceAll]);
         STR11 := StringReplace(STR10, 'B', 'β', [rfReplaceAll]);
         STR12 := StringReplace(STR11, 'CUE', 'kUE', [rfReplaceAll]);
         STR13 := StringReplace(STR12, 'CUI', 'kUI', [rfReplaceAll]);
         STR14 := StringReplace(STR13, 'C', 'k', [rfReplaceAll]);
         STR15 := StringReplace(STR14, 'TkH', 'CH', [rfReplaceAll]);
         STR16 := StringReplace(STR15, 'kH', 'CH', [rfReplaceAll]);
         STR17 := StringReplace(STR16, 'CH', 'ʧ', [rfReplaceAll]);
         STR18 := StringReplace(STR17, 'D', 'd', [rfReplaceAll]);
         STR19 := StringReplace(STR18, 'NG', 'ŋ', [rfReplaceAll]);
         STR20 := StringReplace(STR19, 'G', 'ɣ', [rfReplaceAll]);
         STR21 := StringReplace(STR20, 'M', 'm', [rfReplaceAll]);
         STR22 := StringReplace(STR21, 'N', 'n̪', [rfReplaceAll]);
         STR23 := StringReplace(STR22, 'NH', 'Ñ', [rfReplaceAll]);
         STR24 := StringReplace(STR23, 'Ñ', 'ɲ', [rfReplaceAll]);
         STR25 := StringReplace(STR24, 'P', 'p', [rfReplaceAll]);
         STR26 := StringReplace(STR25, 'QUE', 'kE', [rfReplaceAll]);
         STR27 := StringReplace(STR26, 'QUI', 'kI', [rfReplaceAll]);
         STR28 := StringReplace(STR27, 'Q', 'k', [rfReplaceAll]);
         STR29 := StringReplace(STR28, 'R', 'ɾ', [rfReplaceAll]);
         STR30 := StringReplace(STR29, 'T', 't̪', [rfReplaceAll]);
         STR31 := StringReplace(STR30, 'W', 'ɰ', [rfReplaceAll]);
         STR32 := StringReplace(STR31, 'Y', 'd͡ʒ', [rfReplaceAll]);
         STR33 := StringReplace(STR32, 'J', 'd͡ʒ', [rfReplaceAll]);
         STR34 := StringReplace(STR33, 'F', 'ɸ', [rfReplaceAll]);
         STR35 := StringReplace(STR34, 'L', 'l', [rfReplaceAll]);
         STR36 := StringReplace(STR35, 'Z', 'S', [rfReplaceAll]);
         STR37 := StringReplace(STR36, 'Ç', 'S', [rfReplaceAll]);
         STR38 := StringReplace(STR37, 'S', 's̺', [rfReplaceAll]);
         STR39 := StringReplace(STR38, 'V', 'ɰ', [rfReplaceAll]);
         STR40 := StringReplace(STR39, 'b', 'β', [rfReplaceAll]);
         STR41 := StringReplace(STR40, 'cue', 'kue', [rfReplaceAll]);
         STR42 := StringReplace(STR41, 'Cue', 'kue', [rfReplaceAll]);
         STR43 := StringReplace(STR42, 'cui', 'kui', [rfReplaceAll]);
         STR44 := StringReplace(STR43, 'Cui', 'kui', [rfReplaceAll]);
         STR45 := StringReplace(STR44, 'c', 'k', [rfReplaceAll]);
         STR46 := StringReplace(STR45, 'tkh', 'ch', [rfReplaceAll]);
         STR47 := StringReplace(STR46, 'Tkh', 'ch', [rfReplaceAll]);
         STR48 := StringReplace(STR47, 'kh', 'ch', [rfReplaceAll]);
         STR49 := StringReplace(STR48, 'Kh', 'ch', [rfReplaceAll]);
         STR50 := StringReplace(STR49, 'ch', 'ʧ', [rfReplaceAll]);
         STR51 := StringReplace(STR50, 'd', 'd', [rfReplaceAll]);
         STR52 := StringReplace(STR51, 'ng', 'ŋ', [rfReplaceAll]);
         STR53 := StringReplace(STR52, 'g', 'ɣ', [rfReplaceAll]);
         STR54 := StringReplace(STR53, 'n', 'n̪', [rfReplaceAll]);
         STR55 := StringReplace(STR54, 'nh', 'ñ', [rfReplaceAll]);
         STR56 := StringReplace(STR55, 'Nh', 'ñ', [rfReplaceAll]);
         STR57 := StringReplace(STR56, 'ñ', 'ɲ', [rfReplaceAll]);
         STR58 := StringReplace(STR57, 'que', 'ke', [rfReplaceAll]);
         STR59 := StringReplace(STR58, 'Que', 'ke', [rfReplaceAll]);
         STR60 := StringReplace(STR59, 'qui', 'ki', [rfReplaceAll]);
         STR61 := StringReplace(STR60, 'Qui', 'ki', [rfReplaceAll]);
         STR62 := StringReplace(STR61, 'q', 'k', [rfReplaceAll]);
         STR63 := StringReplace(STR62, 'r', 'ɾ', [rfReplaceAll]);
         STR64 := StringReplace(STR63, 't', 't̪', [rfReplaceAll]);
         STR65 := StringReplace(STR64, 'y', 'd͡ʒ', [rfReplaceAll]);
         STR66 := StringReplace(STR65, 'j', 'd͡ʒ', [rfReplaceAll]);
         STR67 := StringReplace(STR66, 'f', 'ɸ', [rfReplaceAll]);
         STR68 := StringReplace(STR67, 'z', 's', [rfReplaceAll]);
         STR69 := StringReplace(STR68, 'ç', 's', [rfReplaceAll]);
         STR70 := StringReplace(STR69, 's', 's̺', [rfReplaceAll]);
         STR71 := StringReplace(STR70, 'v', 'ɰ', [rfReplaceAll]);
         STR72 := StringReplace(STR71, 'ɡ', 'ɣ', [rfReplaceAll]);
         STR73 := StringReplace(STR72, 'ã', 'ɑ̃', [rfReplaceAll]);
         STR74 := StringReplace(STR73, 'õ', 'ɔ̝̃', [rfReplaceAll]);
         STR75 := StringReplace(STR74, 'ũ', 'ʊ̃', [rfReplaceAll]);
         STR76 := StringReplace(STR75, 'ü̃', 'ɯ̃', [rfReplaceAll]);
         STR77 := StringReplace(STR76, 'a̱', 'ʌ̞', [rfReplaceAll]);
         STR78 := StringReplace(STR77, 'e̱', 'ɛ̝̈', [rfReplaceAll]);
         STR79 := StringReplace(STR78, 'i̱', 'ɪ', [rfReplaceAll]);
         STR80 := StringReplace(STR79, 'o̱', 'ɔ̝̈', [rfReplaceAll]);
         STR81 := StringReplace(STR80, 'u̱', 'ʊ̱', [rfReplaceAll]);
         STR82 := StringReplace(STR81, 'ü̱', 'ɯ', [rfReplaceAll]);
         STR83 := StringReplace(STR82, 'á', 'a', [rfReplaceAll]);
         STR84 := StringReplace(STR83, 'é', 'ɛ̝', [rfReplaceAll]);
         STR85 := StringReplace(STR84, 'í', 'i', [rfReplaceAll]);
         STR86 := StringReplace(STR85, 'ó', 'o', [rfReplaceAll]);
         STR87 := StringReplace(STR86, 'ú', 'ʊ', [rfReplaceAll]);
         STR88 := StringReplace(STR87, 'ǘ', 'ü', [rfReplaceAll]);
         STR89 := StringReplace(STR88, 'à', 'a', [rfReplaceAll]);
         STR90 := StringReplace(STR89, 'è', 'ɛ̝', [rfReplaceAll]);
         STR91 := StringReplace(STR90, 'ì', 'i', [rfReplaceAll]);
         STR92 := StringReplace(STR91, 'ò', 'o', [rfReplaceAll]);
         STR93 := StringReplace(STR92, 'ù', 'ʊ', [rfReplaceAll]);
         STR94 := StringReplace(STR93, 'ǜ', 'ü', [rfReplaceAll]);
         STR95 := StringReplace(STR94, 'w', 'ɰ', [rfReplaceAll]);
         STR96 := StringReplace(STR95, 'd͡ʒae', 'd͡ʒæː', [rfReplaceAll]);
         STR97 := StringReplace(STR96, 'a', 'ɑ̈', [rfReplaceAll]);
         STR98 := StringReplace(STR97, 'e', 'ɛ̝', [rfReplaceAll]);
         STR99 := StringReplace(STR98, 'o', 'ɔ̝', [rfReplaceAll]);
         STR100 := StringReplace(STR99, 'u', 'ʊ', [rfReplaceAll]);
         STR101 := StringReplace(STR100, 'ü', 'ɯ̈', [rfReplaceAll]);
         STR102 := StringReplace(STR101, 'Ã', 'ɑ̃', [rfReplaceAll]);
         STR103 := StringReplace(STR102, 'Ẽ', 'ɛ̝̃', [rfReplaceAll]);
         STR104 := StringReplace(STR103, 'Ĩ', 'ĩ', [rfReplaceAll]);
         STR105 := StringReplace(STR104, 'Õ', 'ɔ̝̃', [rfReplaceAll]);
         STR106 := StringReplace(STR105, 'Ũ', 'ʊ̃', [rfReplaceAll]);
         STR107 := StringReplace(STR106, 'Ü̃', 'ɯ̃', [rfReplaceAll]);
         STR108 := StringReplace(STR107, 'A̱', 'ʌ̞', [rfReplaceAll]);
         STR109 := StringReplace(STR108, 'E̱', 'ɛ̝̈', [rfReplaceAll]);
         STR110 := StringReplace(STR109, 'I̱', 'ɪ', [rfReplaceAll]);
         STR111 := StringReplace(STR110, 'O̱', 'ɔ̝̈', [rfReplaceAll]);
         STR112 := StringReplace(STR111, 'U̱', 'ʊ̱', [rfReplaceAll]);
         STR113 := StringReplace(STR112, 'Ü̱', 'ɯ', [rfReplaceAll]);
         STR114 := StringReplace(STR113, 'Á', 'ɑ̈', [rfReplaceAll]);
         STR115 := StringReplace(STR114, 'É', 'ɛ̝', [rfReplaceAll]);
         STR116 := StringReplace(STR115, 'Í', 'i', [rfReplaceAll]);
         STR117 := StringReplace(STR116, 'Ó', 'ɔ̝', [rfReplaceAll]);
         STR118 := StringReplace(STR117, 'Ú', 'ʊ', [rfReplaceAll]);
         STR119 := StringReplace(STR118, 'Ǘ', 'Ü', [rfReplaceAll]);
         STR120 := StringReplace(STR119, 'À', 'ɑ̈', [rfReplaceAll]);
         STR121 := StringReplace(STR120, 'È', 'ɛ̝', [rfReplaceAll]);
         STR122 := StringReplace(STR121, 'Ì', 'i', [rfReplaceAll]);
         STR123 := StringReplace(STR122, 'Ò', 'ɔ̝', [rfReplaceAll]);
         STR124 := StringReplace(STR123, 'Ù', 'ʊ', [rfReplaceAll]);
         STR125 := StringReplace(STR124, 'Ǜ', 'Ü', [rfReplaceAll]);
         STR126 := StringReplace(STR125, 'd͡ʒAE', 'd͡ʒæː', [rfReplaceAll]);
         STR127 := StringReplace(STR126, 'A', 'ɑ̈', [rfReplaceAll]);
         STR128 := StringReplace(STR127, 'E', 'ɛ̝', [rfReplaceAll]);
         STR129 := StringReplace(STR128, 'I', 'i', [rfReplaceAll]);
         STR130 := StringReplace(STR129, 'O', 'ɔ̝', [rfReplaceAll]);
         STR131 := StringReplace(STR130, 'U', 'ʊ', [rfReplaceAll]);
         STR132 := StringReplace(STR131, 'Ü', 'ɯ̈', [rfReplaceAll]);
         STR133 := StringReplace(STR132, '.', ' ∥', [rfReplaceAll]);
         STR134 := StringReplace(STR133, ',', ' ∣', [rfReplaceAll]);
         STR135 := StringReplace(STR134, ';', ' ∥', [rfReplaceAll]);
         STR136 := StringReplace(STR135, ':', ' ∣', [rfReplaceAll]);
         STR137 := StringReplace(STR136, '?', ' ∥', [rfReplaceAll]);
         STR138 := StringReplace(STR137, '¿', '', [rfReplaceAll]);
         STR139 := StringReplace(STR138, '!', ' ∥', [rfReplaceAll]);
         STR140 := StringReplace(STR139, '¡', '', [rfReplaceAll]);
         STR141 := StringReplace(STR140, ' - ', ' ∣ ', [rfReplaceAll]);
         STR142 := StringReplace(STR141, ' – ', ' ∣ ', [rfReplaceAll]);
         STR143 := StringReplace(STR142, '(', '∣ ', [rfReplaceAll]);
         STR144 := StringReplace(STR143, ')', ' ∣', [rfReplaceAll]);
         STR145 := StringReplace(STR144, 'n̪̪ɣ', 'ŋ', [rfReplaceAll]);
         Writeln('');
         TextColor(7);
         Writeln('Eastern Tikuna (Umariaçu, Brazil):');
         Writeln('');
         TextColor(15);
         Writeln('   ',STR145);
         TextColor(7);
         Writeln('');
         Halt;
      End;

   End;

   { ORTHOGRAPHY }

   If INPUT1 = '--ort' Then
   Begin

   { NO LANGUAGE SELECTED  }

      If INPUT2 ='' Then
      Begin
         TextColor(4);
         Writeln('Error:    No language selected! Add: [OPTION_2]');
         Writeln('');
         GoTo HELP;
      End;

   { ORTHOGRAPHY: ENGLISH }

      If INPUT2 = '--eng' Then
      Begin
   { EMPTY ENGLISH STRING }
         If INPUT3 = '' Then
         Begin
            TextColor(4);
            Writeln('Error:    No string inserted! Add: [STRING]');
            Writeln('');
            GoTo HELP;
         End;

         STR1 := INPUT3;
         STR2 := StringReplace(STR1, 'celling', 'celing', [rfReplaceAll]);
         STR3 := StringReplace(STR2, 'delling', 'deling', [rfReplaceAll]);
         STR4 := StringReplace(STR3, 'velling', 'veling', [rfReplaceAll]);
         STR5 := StringReplace(STR4, 'bour', 'bor', [rfReplaceAll]);
         STR6 := StringReplace(STR5, 'iour', 'ior', [rfReplaceAll]);
         STR7 := StringReplace(STR6, 'nour', 'nor', [rfReplaceAll]);
         STR8 := StringReplace(STR7, 'olour', 'olor', [rfReplaceAll]);
         STR9 := StringReplace(STR8, 'centre', 'center', [rfReplaceAll]);
         STR10 := StringReplace(STR9, 'metre', 'meter', [rfReplaceAll]);
         STR11 := StringReplace(STR10, 'theatre', 'theater', [rfReplaceAll]);
         STR12 := StringReplace(STR11, 'fence', 'fense', [rfReplaceAll]);
         STR13 := StringReplace(STR12, 'lise', 'lize', [rfReplaceAll]);
         STR14 := StringReplace(STR13, 'lyse', 'lyze', [rfReplaceAll]);
         STR15 := StringReplace(STR14, 'sation', 'zation', [rfReplaceAll]);
         STR16 := StringReplace(STR15, 'aestetic', 'estetic', [rfReplaceAll]);
         STR17 := StringReplace(STR16, 'Aestetic', 'Estetic', [rfReplaceAll]);
         STR18 := StringReplace(STR17, 'faec', 'fec', [rfReplaceAll]);
         STR19 := StringReplace(STR18, 'Faec', 'Fec', [rfReplaceAll]);
         STR20 := StringReplace(STR19, 'palaeo', 'paleo', [rfReplaceAll]);
         STR21 := StringReplace(STR20, 'Palaeo', 'Paleo', [rfReplaceAll]);
         STR22 := StringReplace(STR21, 'manoeuvre', 'maneuver', [rfReplaceAll]);
         STR23 := StringReplace(STR22, 'aluminium', 'aluminum', [rfReplaceAll]);
         STR24 := StringReplace(STR23, 'Aluminium', 'Aluminum', [rfReplaceAll]);
         STR25 := StringReplace(STR24, ' axe ', ' ax ', [rfReplaceAll]);
         STR26 := StringReplace(STR25, ' axe,', ' ax,', [rfReplaceAll]);
         STR27 := StringReplace(STR26, ' axe.', ' ax.', [rfReplaceAll]);
         STR28 := StringReplace(STR27, 'cheque', 'check', [rfReplaceAll]);
         STR29 := StringReplace(STR28, 'cumquat', 'kumquat', [rfReplaceAll]);
         STR30 := StringReplace(STR29, 'fulfil ', 'fulfill ', [rfReplaceAll]);
         STR31 := StringReplace(STR30, 'Fulfil ', 'Fulfill ', [rfReplaceAll]);
         STR32 := StringReplace(STR31, 'grey', 'gray', [rfReplaceAll]);
         STR33 := StringReplace(STR32, 'Grey', 'Gray', [rfReplaceAll]);
         STR34 := StringReplace(STR33, 'kerb', 'curb', [rfReplaceAll]);
         STR35 := StringReplace(STR34, 'moustache', 'mustache', [rfReplaceAll]);
         STR36 := StringReplace(STR35, 'mum ', 'mom ', [rfReplaceAll]);
         STR37 := StringReplace(STR36, 'mum,', 'mom,', [rfReplaceAll]);
         STR38 := StringReplace(STR37, 'mum.', 'mom.', [rfReplaceAll]);
         STR39 := StringReplace(STR38, 'Mum,', 'Mom,', [rfReplaceAll]);
         STR40 := StringReplace(STR39, 'programme', 'program', [rfReplaceAll]);
         STR41 := StringReplace(STR40, 'Programme', 'Program', [rfReplaceAll]);
         STR42 := StringReplace(STR41, 'sceptical', 'skeptical', [rfReplaceAll]);
         STR43 := StringReplace(STR42, 'Sceptical', 'Skeptical', [rfReplaceAll]);
         STR44 := StringReplace(STR43, 'CELLING', 'CELING', [rfReplaceAll]);
         STR45 := StringReplace(STR44, 'DELLING', 'DELING', [rfReplaceAll]);
         STR46 := StringReplace(STR45, 'VELLING', 'VELING', [rfReplaceAll]);
         STR47 := StringReplace(STR46, 'BOUR', 'BOR', [rfReplaceAll]);
         STR48 := StringReplace(STR47, 'IOUR', 'IOR', [rfReplaceAll]);
         STR49 := StringReplace(STR48, 'NOUR', 'NOR', [rfReplaceAll]);
         STR50 := StringReplace(STR49, 'OLOUR', 'OLOR', [rfReplaceAll]);
         STR51 := StringReplace(STR50, 'CENTRE', 'CENTER', [rfReplaceAll]);
         STR52 := StringReplace(STR51, 'METRE', 'METER', [rfReplaceAll]);
         STR53 := StringReplace(STR52, 'THEATRE', 'THEATER', [rfReplaceAll]);
         STR54 := StringReplace(STR53, 'FENCE', 'FENSE', [rfReplaceAll]);
         STR55 := StringReplace(STR54, 'LISE', 'LIZE', [rfReplaceAll]);
         STR56 := StringReplace(STR55, 'LYSE', 'LYZE', [rfReplaceAll]);
         STR57 := StringReplace(STR56, 'SATION', 'ZATION', [rfReplaceAll]);
         STR58 := StringReplace(STR57, 'AESTETIC', 'ESTETIC', [rfReplaceAll]);
         STR59 := StringReplace(STR58, 'FAEC', 'FEC', [rfReplaceAll]);
         STR60 := StringReplace(STR59, 'PALAEO', 'PALEO', [rfReplaceAll]);
         STR61 := StringReplace(STR60, 'MANOEUVRE', 'MANEUVER', [rfReplaceAll]);
         STR62 := StringReplace(STR61, 'ALUMINIUM', 'ALUMINUM', [rfReplaceAll]);
         STR63 := StringReplace(STR62, ' AXE ', ' AX ', [rfReplaceAll]);
         STR64 := StringReplace(STR63, ' AXE,', ' AX,', [rfReplaceAll]);
         STR65 := StringReplace(STR64, ' AXE.', ' AX.', [rfReplaceAll]);
         STR66 := StringReplace(STR65, 'CHEQUE', 'CHECK', [rfReplaceAll]);
         STR67 := StringReplace(STR66, 'CUMQUAT', 'KUMQUAT', [rfReplaceAll]);
         STR68 := StringReplace(STR67, 'FULFIL ', 'FULFILL ', [rfReplaceAll]);
         STR69 := StringReplace(STR68, 'GREY', 'GRAY', [rfReplaceAll]);
         STR70 := StringReplace(STR69, 'KERB', 'CURB', [rfReplaceAll]);
         STR71 := StringReplace(STR70, 'MOUSTACHE', 'MUSTACHE', [rfReplaceAll]);
         STR72 := StringReplace(STR71, 'MUM ', 'MOM ', [rfReplaceAll]);
         STR73 := StringReplace(STR72, 'MUM,', 'MOM,', [rfReplaceAll]);
         STR74 := StringReplace(STR73, 'MUM.', 'MOM.', [rfReplaceAll]);
         STR75 := StringReplace(STR74, 'PROGRAMME', 'PROGRAM', [rfReplaceAll]);
         STR76 := StringReplace(STR75, 'SCEPTICAL', 'SKEPTICAL', [rfReplaceAll]);
         Writeln('');
         Writeln('Spelling of American English:');
         Writeln('');
         TextColor(15);
         Writeln('   ',STR76);
         TextColor(7);
         Writeln('');
         Halt;
      End;

   { ORTHOGRAPHY: LATIN }

      If INPUT2 = '--lat' Then
      Begin
   { EMPTY LATIN STRING }
         If INPUT3 = '' Then
         Begin
            TextColor(4);
            Writeln('Error:    No string inserted! Add: [STRING]');
            Writeln('');
            GoTo HELP;
         End;

         STR1 := INPUT3;
         STR2 := StringReplace(STR1, 'a', 'A', [rfReplaceAll]);
         STR3 := StringReplace(STR2, 'á', 'Á', [rfReplaceAll]);
         STR4 := StringReplace(STR3, 'ă', 'A', [rfReplaceAll]);
         STR5 := StringReplace(STR4, 'ā', 'Á', [rfReplaceAll]);
         STR6 := StringReplace(STR5, 'b', 'B', [rfReplaceAll]);
         STR7 := StringReplace(STR6, 'c', 'C', [rfReplaceAll]);
         STR8 := StringReplace(STR7, 'd', 'D', [rfReplaceAll]);
         STR9 := StringReplace(STR8, 'e', 'E', [rfReplaceAll]);
         STR10 := StringReplace(STR9, 'ĕ', 'E', [rfReplaceAll]);
         STR11 := StringReplace(STR10, 'é', 'É', [rfReplaceAll]);
         STR12 := StringReplace(STR11, 'ē', 'É', [rfReplaceAll]);
         STR13 := StringReplace(STR12, 'ë', 'E', [rfReplaceAll]);
         STR14 := StringReplace(STR13, 'f', 'F', [rfReplaceAll]);
         STR15 := StringReplace(STR14, 'g', 'G', [rfReplaceAll]);
         STR16 := StringReplace(STR15, 'h', 'H', [rfReplaceAll]);
         STR17 := StringReplace(STR16, 'i', 'I', [rfReplaceAll]);
         STR18 := StringReplace(STR17, 'ĭ', 'I', [rfReplaceAll]);
         STR19 := StringReplace(STR18, 'Ī', 'ꟾ', [rfReplaceAll]);
         STR20 := StringReplace(STR19, 'ī', 'ꟾ', [rfReplaceAll]);
         STR21 := StringReplace(STR20, 'í', 'ꟾ', [rfReplaceAll]);
         STR22 := StringReplace(STR21, 'Í', 'ꟾ', [rfReplaceAll]);
         STR23 := StringReplace(STR22, 'j', 'I', [rfReplaceAll]);
         STR24 := StringReplace(STR23, 'k', 'K', [rfReplaceAll]);
         STR25 := StringReplace(STR24, 'l', 'L', [rfReplaceAll]);
         STR26 := StringReplace(STR25, 'm', 'M', [rfReplaceAll]);
         STR27 := StringReplace(STR26, 'n', 'N', [rfReplaceAll]);
         STR28 := StringReplace(STR27, 'o', 'O', [rfReplaceAll]);
         STR29 := StringReplace(STR28, 'ŏ', 'O', [rfReplaceAll]);
         STR30 := StringReplace(STR29, 'ō', 'Ó', [rfReplaceAll]);
         STR31 := StringReplace(STR30, 'p', 'P', [rfReplaceAll]);
         STR32 := StringReplace(STR31, 'q', 'Q', [rfReplaceAll]);
         STR33 := StringReplace(STR32, 'r', 'R', [rfReplaceAll]);
         STR34 := StringReplace(STR33, 's', 'S', [rfReplaceAll]);
         STR35 := StringReplace(STR34, 't', 'T', [rfReplaceAll]);
         STR36 := StringReplace(STR35, 'u', 'V', [rfReplaceAll]);
         STR37 := StringReplace(STR36, 'v', 'V', [rfReplaceAll]);
         STR38 := StringReplace(STR37, 'ú', 'Ú', [rfReplaceAll]);
         STR39 := StringReplace(STR38, 'ŭ', 'V', [rfReplaceAll]);
         STR40 := StringReplace(STR39, 'ū', 'Ú', [rfReplaceAll]);
         STR41 := StringReplace(STR40, 'ü', 'V', [rfReplaceAll]);
         STR42 := StringReplace(STR41, 'w', 'VV', [rfReplaceAll]);
         STR43 := StringReplace(STR42, 'x', 'X', [rfReplaceAll]);
         STR44 := StringReplace(STR43, 'y', 'Y', [rfReplaceAll]);
         STR45 := StringReplace(STR44, 'y̆', 'Y', [rfReplaceAll]);
         STR46 := StringReplace(STR45, 'ȳ', 'Ý', [rfReplaceAll]);
         STR47 := StringReplace(STR46, 'ý', 'Ý', [rfReplaceAll]);
         STR48 := StringReplace(STR47, 'z', 'Z', [rfReplaceAll]);
         STR49 := StringReplace(STR48, ' - ', '·', [rfReplaceAll]);
         STR50 := StringReplace(STR49, '--', '·', [rfReplaceAll]);
         STR51 := StringReplace(STR50, '–', '·', [rfReplaceAll]);
         STR52 := StringReplace(STR51, ', ', '·', [rfReplaceAll]);
         STR53 := StringReplace(STR52, '; ', '·', [rfReplaceAll]);
         STR54 := StringReplace(STR53, ': ', '·', [rfReplaceAll]);
         STR55 := StringReplace(STR54, '. ', '·', [rfReplaceAll]);
         STR56 := StringReplace(STR55, '! ', '·', [rfReplaceAll]);
         STR57 := StringReplace(STR56, '? ', '·', [rfReplaceAll]);
         STR58 := StringReplace(STR57, '.', '·', [rfReplaceAll]);
         STR59 := StringReplace(STR58, '!', '·', [rfReplaceAll]);
         STR60 := StringReplace(STR59, '?', '·', [rfReplaceAll]);
         STR61 := StringReplace(STR60, ' ', '·', [rfReplaceAll]);
         STR62 := StringReplace(STR61, 'Ă', 'A', [rfReplaceAll]);
         STR63 := StringReplace(STR62, 'Ā', 'Á', [rfReplaceAll]);
         STR64 := StringReplace(STR63, 'Ĕ', 'E', [rfReplaceAll]);
         STR65 := StringReplace(STR64, 'Ë', 'E', [rfReplaceAll]);
         STR66 := StringReplace(STR65, 'Ĭ', 'I', [rfReplaceAll]);
         STR67 := StringReplace(STR66, 'Ī', 'ꟾ', [rfReplaceAll]);
         STR68 := StringReplace(STR67, 'Í', 'ꟾ', [rfReplaceAll]);
         STR69 := StringReplace(STR68, 'J', 'I', [rfReplaceAll]);
         STR70 := StringReplace(STR69, 'Ŏ', 'O', [rfReplaceAll]);
         STR71 := StringReplace(STR70, 'Ō', 'Ó', [rfReplaceAll]);
         STR72 := StringReplace(STR71, 'Ŭ', 'V', [rfReplaceAll]);
         STR73 := StringReplace(STR72, 'Ū', 'Ú', [rfReplaceAll]);
         STR74 := StringReplace(STR73, 'Ü', 'V', [rfReplaceAll]);
         STR75 := StringReplace(STR74, 'Y̆', 'Y', [rfReplaceAll]);
         STR76 := StringReplace(STR75, 'Ȳ', 'Ý', [rfReplaceAll]);
         Writeln('');
         Writeln('Classical Latin:');
         Writeln('');
         TextColor(15);
         Writeln('   ',STR76);
         TextColor(7);
         Writeln('');
         Halt;
      End;

   { ORTHOGRAPHY: QUECHUA }

      If INPUT2 = '--qwe' Then
      Begin
   { EMPTY QUECHUAN STRING }
         If INPUT3 = '' Then
         Begin
            TextColor(4);
            Writeln('Error:    No string inserted! Add: [STRING]');
            Writeln('');
            GoTo HELP;
         End;
   { TRIVOCALIC }
         STR1 := INPUT3;
         STR2 := StringReplace(STR1, 'o', 'u', [rfReplaceAll]);
         STR3 := StringReplace(STR2, 'O', 'U', [rfReplaceAll]);
         STR4 := StringReplace(STR3, 'e', 'i', [rfReplaceAll]);
         STR5 := StringReplace(STR4, 'E', 'I', [rfReplaceAll]);
         Writeln('');
         Writeln('Trivocalic orthographic convention:');
         Writeln('');
         TextColor(15);
         Writeln('   ',STR5);
   { PENTAVOCALIC }
         STR1 := INPUT3;
         STR2 := StringReplace(STR1, 'qu', 'qo', [rfReplaceAll]);
         STR3 := StringReplace(STR2, 'Qu', 'Qo', [rfReplaceAll]);
         STR4 := StringReplace(STR3, 'QU', 'QO', [rfReplaceAll]);
         STR5 := StringReplace(STR4, 'qi', 'qe', [rfReplaceAll]);
         STR6 := StringReplace(STR5, 'Qi', 'Qe', [rfReplaceAll]);
         STR7 := StringReplace(STR6, 'QI', 'QE', [rfReplaceAll]);
         STR8 := StringReplace(STR7, 'qhu', 'qho', [rfReplaceAll]);
         STR9 := StringReplace(STR8, 'Qhu', 'Qho', [rfReplaceAll]);
         STR10 := StringReplace(STR9, 'QHU', 'QHO', [rfReplaceAll]);
         STR11 := StringReplace(STR10, 'qhi', 'qhe', [rfReplaceAll]);
         STR12 := StringReplace(STR11, 'Qhi', 'Qhe', [rfReplaceAll]);
         STR13 := StringReplace(STR12, 'QHI', 'QHE', [rfReplaceAll]);
         STR14 := StringReplace(STR13, 'ko', 'ku', [rfReplaceAll]);
         STR15 := StringReplace(STR14, 'Ko', 'Ku', [rfReplaceAll]);
         STR16 := StringReplace(STR15, 'KO', 'KU', [rfReplaceAll]);
         STR17 := StringReplace(STR16, 'ke', 'ki', [rfReplaceAll]);
         STR18 := StringReplace(STR17, 'Ke', 'Ki', [rfReplaceAll]);
         STR19 := StringReplace(STR18, 'KE', 'KI', [rfReplaceAll]);
         STR20 := StringReplace(STR19, 'kho', 'khu', [rfReplaceAll]);
         STR21 := StringReplace(STR20, 'Kho', 'Khu', [rfReplaceAll]);
         STR22 := StringReplace(STR21, 'KHO', 'KHU', [rfReplaceAll]);         
         STR23 := StringReplace(STR22, 'khe', 'khi', [rfReplaceAll]);
         STR24 := StringReplace(STR23, 'Khe', 'Khi', [rfReplaceAll]);
         STR25 := StringReplace(STR24, 'KHE', 'KHI', [rfReplaceAll]);
         STR26 := StringReplace(STR25, 'q''u', 'q''o', [rfReplaceAll]);
         STR27 := StringReplace(STR26, 'Q''u', 'Q''o', [rfReplaceAll]);
         STR28 := StringReplace(STR27, 'Q''U', 'Q''O', [rfReplaceAll]);
         STR29 := StringReplace(STR28, 'q''i', 'q''e', [rfReplaceAll]);
         STR30 := StringReplace(STR29, 'Q''i', 'Q''e', [rfReplaceAll]);
         STR31 := StringReplace(STR30, 'Q''I', 'Q''E', [rfReplaceAll]);
         STR32 := StringReplace(STR31, 'q’u', 'q’o', [rfReplaceAll]);
         STR33 := StringReplace(STR32, 'Q’u', 'Q’o', [rfReplaceAll]);
         STR34 := StringReplace(STR33, 'Q’U', 'Q’O', [rfReplaceAll]);         
         STR35 := StringReplace(STR34, 'q’i', 'q’e', [rfReplaceAll]);
         STR36 := StringReplace(STR35, 'Q’i', 'Q’e', [rfReplaceAll]);
         STR37 := StringReplace(STR36, 'Q’I', 'Q’E', [rfReplaceAll]);
         STR38 := StringReplace(STR37, 'uq', 'oq', [rfReplaceAll]);
         STR39 := StringReplace(STR38, 'Uq', 'Oq', [rfReplaceAll]);
         STR40 := StringReplace(STR39, 'UQ', 'OQ', [rfReplaceAll]);
         STR41 := StringReplace(STR40, 'iq', 'eq', [rfReplaceAll]);
         STR42 := StringReplace(STR41, 'Iq', 'Eq', [rfReplaceAll]);
         STR43 := StringReplace(STR42, 'IQ', 'EQ', [rfReplaceAll]);
         Writeln('');
         TextColor(7);
         Writeln('Pentavocalic orthographic convention:');
         Writeln('');
         TextColor(15);
         Writeln('   ',STR31);
         TextColor(7);
         Writeln('');
         Halt;
      End;

   { ORTHOGRAPHY: TIKUNA }

      If INPUT2 = '--tca' Then
      Begin
   { EMPTY TIKUNA STRING }
         If INPUT3 = '' Then
         Begin
            TextColor(4);
            Writeln('Error:    No string inserted! Add: [STRING]');
            Writeln('');
            GoTo HELP;
         End;
   { TIKUNA: BRAZIL }
         STR1 := INPUT3;
         STR2 := StringReplace(STR1, 'y', 'j', [rfReplaceAll]);
         STR3 := StringReplace(STR2, 'Y', 'J', [rfReplaceAll]);
         STR4 := StringReplace(STR3, 'ch', 'tch', [rfReplaceAll]);
         STR5 := StringReplace(STR4, 'Ch', 'Tch', [rfReplaceAll]);
         STR6 := StringReplace(STR5, 'CH', 'TCH', [rfReplaceAll]);
         STR7 := StringReplace(STR6, 'ttch', 'tch', [rfReplaceAll]);
         STR8 := StringReplace(STR7, 'TTCH', 'TCH', [rfReplaceAll]);
         STR9 := StringReplace(STR8, 'ñ', 'nh', [rfReplaceAll]);
         STR10 := StringReplace(STR9, 'Ñ', 'NH', [rfReplaceAll]);
         STR11 := StringReplace(STR10, 'ka', 'ca', [rfReplaceAll]);
         STR12 := StringReplace(STR11, 'Ka', 'Ca', [rfReplaceAll]);
         STR13 := StringReplace(STR12, 'KA', 'CA', [rfReplaceAll]);
         STR14 := StringReplace(STR13, 'ka̱', 'ca', [rfReplaceAll]);
         STR15 := StringReplace(STR14, 'Ka̱', 'Ca', [rfReplaceAll]);
         STR16 := StringReplace(STR15, 'KA̱', 'CA', [rfReplaceAll]);
         STR17 := StringReplace(STR16, 'ká', 'cá', [rfReplaceAll]);
         STR18 := StringReplace(STR17, 'Ká', 'Cá', [rfReplaceAll]);
         STR19 := StringReplace(STR18, 'KÁ', 'CÁ', [rfReplaceAll]);
         STR20 := StringReplace(STR19, 'ko', 'co', [rfReplaceAll]);
         STR21 := StringReplace(STR20, 'Ko', 'Co', [rfReplaceAll]);
         STR22 := StringReplace(STR21, 'KO', 'CO', [rfReplaceAll]);
         STR23 := StringReplace(STR22, 'kõ', 'cõ', [rfReplaceAll]);
         STR24 := StringReplace(STR23, 'Kõ', 'Cõ', [rfReplaceAll]);
         STR25 := StringReplace(STR24, 'KÕ', 'CÕ', [rfReplaceAll]);
         STR26 := StringReplace(STR25, 'kó', 'có', [rfReplaceAll]);
         STR27 := StringReplace(STR26, 'Kó', 'Có', [rfReplaceAll]);
         STR28 := StringReplace(STR27, 'KÓ', 'CÓ', [rfReplaceAll]);
         STR29 := StringReplace(STR28, 'ku', 'cu', [rfReplaceAll]);
         STR30 := StringReplace(STR29, 'Ku', 'Cu', [rfReplaceAll]);
         STR31 := StringReplace(STR30, 'KU', 'CU', [rfReplaceAll]);
         STR32 := StringReplace(STR31, 'ku̱', 'cu’', [rfReplaceAll]);
         STR33 := StringReplace(STR32, 'Ku̱', 'Cu’', [rfReplaceAll]);
         STR34 := StringReplace(STR33, 'KU̱', 'CU’', [rfReplaceAll]);
         STR35 := StringReplace(STR34, 'kú', 'cú', [rfReplaceAll]);
         STR36 := StringReplace(STR35, 'Kú', 'Cú', [rfReplaceAll]);
         STR37 := StringReplace(STR36, 'KÚ', 'CÚ', [rfReplaceAll]);
         STR38 := StringReplace(STR37, 'kü', 'cü', [rfReplaceAll]);
         STR39 := StringReplace(STR38, 'Kü', 'Cü', [rfReplaceAll]);
         STR40 := StringReplace(STR39, 'KÜ', 'CÜ', [rfReplaceAll]);
         STR41 := StringReplace(STR40, 'kü’', 'cü’', [rfReplaceAll]);
         STR42 := StringReplace(STR41, 'Kü’', 'Cü’', [rfReplaceAll]);
         STR43 := StringReplace(STR42, 'KÜ’', 'CÜ’', [rfReplaceAll]);
         STR44 := StringReplace(STR43, 'cua', 'qua', [rfReplaceAll]);
         STR45 := StringReplace(STR44, 'Cua', 'Qua', [rfReplaceAll]);
         STR46 := StringReplace(STR45, 'CUA', 'QUA', [rfReplaceAll]);
         STR47 := StringReplace(STR46, 'cua’', 'qua’', [rfReplaceAll]);
         STR48 := StringReplace(STR47, 'Cua̱', 'Qua’', [rfReplaceAll]);
         STR49 := StringReplace(STR48, 'CUA̱', 'QUA’', [rfReplaceAll]);
         STR50 := StringReplace(STR49, 'kua', 'qua', [rfReplaceAll]);
         STR51 := StringReplace(STR50, 'Kua', 'Qua', [rfReplaceAll]);
         STR52 := StringReplace(STR51, 'KUA', 'QUA', [rfReplaceAll]);
         STR53 := StringReplace(STR52, 'kua̱', 'qua’', [rfReplaceAll]);
         STR54 := StringReplace(STR53, 'Kua̱', 'Qua’', [rfReplaceAll]);
         STR55 := StringReplace(STR54, 'KUA̱', 'QUA’', [rfReplaceAll]);
         STR56 := StringReplace(STR55, 'ki', 'qui', [rfReplaceAll]);
         STR57 := StringReplace(STR56, 'Ki', 'Qui', [rfReplaceAll]);
         STR58 := StringReplace(STR57, 'KI', 'QUI', [rfReplaceAll]);
         STR59 := StringReplace(STR58, 'ke', 'que', [rfReplaceAll]);
         STR60 := StringReplace(STR59, 'Ke', 'Que', [rfReplaceAll]);
         STR61 := StringReplace(STR60, 'KE', 'QUE', [rfReplaceAll]);
         STR62 := StringReplace(STR61, 'ax', 'a’', [rfReplaceAll]);
         STR63 := StringReplace(STR62, 'ãx', 'ã’', [rfReplaceAll]);
         STR64 := StringReplace(STR63, 'a̱x', 'a’', [rfReplaceAll]);
         STR65 := StringReplace(STR64, 'ã̱x', 'ã’', [rfReplaceAll]);
         STR66 := StringReplace(STR65, 'áx', 'á’', [rfReplaceAll]);
         STR67 := StringReplace(STR66, 'ex', 'e’', [rfReplaceAll]);
         STR68 := StringReplace(STR67, 'ẽx', 'ẽ’', [rfReplaceAll]);
         STR69 := StringReplace(STR68, 'e̱x', 'e’', [rfReplaceAll]);
         STR70 := StringReplace(STR69, 'ẽ̱x', 'ẽ’', [rfReplaceAll]);
         STR71 := StringReplace(STR70, 'éx', 'é’', [rfReplaceAll]);
         STR72 := StringReplace(STR71, 'ix', 'i’', [rfReplaceAll]);
         STR73 := StringReplace(STR72, 'ĩx', 'ĩ’', [rfReplaceAll]);
         STR74 := StringReplace(STR73, 'íx', 'í’', [rfReplaceAll]);
         STR75 := StringReplace(STR74, 'ox', 'o’', [rfReplaceAll]);
         STR76 := StringReplace(STR75, 'õx', 'õ’', [rfReplaceAll]);
         STR77 := StringReplace(STR76, 'o̱x', 'o’', [rfReplaceAll]);
         STR78 := StringReplace(STR77, 'õ̱x', 'õ’', [rfReplaceAll]);
         STR79 := StringReplace(STR78, 'óx', 'ó’', [rfReplaceAll]);
         STR80 := StringReplace(STR79, 'ux', 'u’', [rfReplaceAll]);
         STR81 := StringReplace(STR80, 'ũx', 'ũ’', [rfReplaceAll]);
         STR82 := StringReplace(STR81, 'u̱x', 'u’', [rfReplaceAll]);
         STR83 := StringReplace(STR82, 'úx', 'ú’', [rfReplaceAll]);
         STR84 := StringReplace(STR83, 'üx', 'ü’', [rfReplaceAll]);
         STR85 := StringReplace(STR84, 'ü̃x', 'ü̃’', [rfReplaceAll]);
         STR86 := StringReplace(STR85, 'ü̱x', 'ü’', [rfReplaceAll]);
         STR87 := StringReplace(STR86, 'ü̱̃x', 'ü̃’', [rfReplaceAll]);
         STR88 := StringReplace(STR87, 'ǘx', 'ǘ’', [rfReplaceAll]);
         STR89 := StringReplace(STR88, 'AX', 'A’', [rfReplaceAll]);
         STR90 := StringReplace(STR89, 'ÃX', 'Ã’', [rfReplaceAll]);
         STR91 := StringReplace(STR90, 'A̱X', 'A’', [rfReplaceAll]);
         STR92 := StringReplace(STR91, 'Ã̱X', 'Ã’', [rfReplaceAll]);
         STR93 := StringReplace(STR92, 'ÁX', 'Á’', [rfReplaceAll]);
         STR94 := StringReplace(STR93, 'EX', 'E’', [rfReplaceAll]);
         STR95 := StringReplace(STR94, 'ẼX', 'Ẽ’', [rfReplaceAll]);
         STR96 := StringReplace(STR95, 'E̱X', 'E’', [rfReplaceAll]);
         STR97 := StringReplace(STR96, 'Ẽ̱X', 'Ẽ’', [rfReplaceAll]);
         STR98 := StringReplace(STR97, 'ÉX', 'É’', [rfReplaceAll]);
         STR99 := StringReplace(STR98, 'IX', 'I’', [rfReplaceAll]);
         STR100 := StringReplace(STR99, 'ĨX', 'Ĩ’', [rfReplaceAll]);
         STR101 := StringReplace(STR100, 'I̱X', 'I’', [rfReplaceAll]);
         STR102 := StringReplace(STR101, 'Ĩ̱X', 'Ĩ’', [rfReplaceAll]);
         STR103 := StringReplace(STR102, 'ÍX', 'Í’', [rfReplaceAll]);
         STR104 := StringReplace(STR103, 'OX', 'O’', [rfReplaceAll]);
         STR105 := StringReplace(STR104, 'ÕX', 'Õ’', [rfReplaceAll]);
         STR106 := StringReplace(STR105, 'O̱X', 'O’', [rfReplaceAll]);
         STR107 := StringReplace(STR106, 'Õ̱X', 'Õ’', [rfReplaceAll]);
         STR108 := StringReplace(STR107, 'ÓX', 'Ó’', [rfReplaceAll]);
         STR109 := StringReplace(STR108, 'UX', 'U’', [rfReplaceAll]);
         STR110 := StringReplace(STR109, 'ŨX', 'Ũ’', [rfReplaceAll]);
         STR111 := StringReplace(STR110, 'U̱X', 'U’', [rfReplaceAll]);
         STR112 := StringReplace(STR111, 'Ũ̱X', 'Ũ’', [rfReplaceAll]);
         STR113 := StringReplace(STR112, 'ÚX', 'Ú’', [rfReplaceAll]);
         STR114 := StringReplace(STR113, 'ÜX', 'Ü’', [rfReplaceAll]);
         STR115 := StringReplace(STR114, 'Ü̃X', 'Ü̃’', [rfReplaceAll]);
         STR116 := StringReplace(STR115, 'Ü̱X', 'Ü’', [rfReplaceAll]);
         STR117 := StringReplace(STR116, 'Ü̱̃X', 'Ü̃’', [rfReplaceAll]);
         STR118 := StringReplace(STR117, 'ǗX', 'Ǘ’', [rfReplaceAll]);
         STR119 := StringReplace(STR118, 'Ax', 'A’', [rfReplaceAll]);
         STR120 := StringReplace(STR119, 'Ãx', 'Ã’', [rfReplaceAll]);
         STR121 := StringReplace(STR120, 'A̱x', 'A’', [rfReplaceAll]);
         STR122 := StringReplace(STR121, 'Ã̱x', 'Ã’', [rfReplaceAll]);
         STR123 := StringReplace(STR122, 'Áx', 'Á’', [rfReplaceAll]);
         STR124 := StringReplace(STR123, 'Ex', 'E’', [rfReplaceAll]);
         STR125 := StringReplace(STR124, 'Ẽx', 'Ẽ’', [rfReplaceAll]);
         STR126 := StringReplace(STR125, 'E̱x', 'E’', [rfReplaceAll]);
         STR127 := StringReplace(STR126, 'Ẽ̱x', 'Ẽ’', [rfReplaceAll]);
         STR128 := StringReplace(STR127, 'Éx', 'É’', [rfReplaceAll]);
         STR129 := StringReplace(STR128, 'Ix', 'I’', [rfReplaceAll]);
         STR130 := StringReplace(STR129, 'Ĩx', 'Ĩ’', [rfReplaceAll]);
         STR131 := StringReplace(STR130, 'Íx', 'Í’', [rfReplaceAll]);
         STR132 := StringReplace(STR131, 'Ox', 'O’', [rfReplaceAll]);
         STR133 := StringReplace(STR132, 'Õx', 'Õ’', [rfReplaceAll]);
         STR134 := StringReplace(STR133, 'O̱x', 'O’', [rfReplaceAll]);
         STR135 := StringReplace(STR134, 'Õ̱x', 'Õ’', [rfReplaceAll]);
         STR136 := StringReplace(STR135, 'Óx', 'Ó’', [rfReplaceAll]);
         STR137 := StringReplace(STR136, 'Ux', 'U’', [rfReplaceAll]);
         STR138 := StringReplace(STR137, 'Ũx', 'Ũ’', [rfReplaceAll]);
         STR139 := StringReplace(STR138, 'U̱x', 'U’', [rfReplaceAll]);
         STR140 := StringReplace(STR139, 'Ũ̱x', 'Ũ’', [rfReplaceAll]);
         STR141 := StringReplace(STR140, 'Úx', 'Ú’', [rfReplaceAll]);
         STR142 := StringReplace(STR141, 'Üx', 'Ü’', [rfReplaceAll]);
         STR143 := StringReplace(STR142, 'Ü̃x', 'Ü̃’', [rfReplaceAll]);
         STR144 := StringReplace(STR143, 'Ü̱x', 'Ü’', [rfReplaceAll]);
         STR145 := StringReplace(STR144, 'Ü̱̃x', 'Ü̃’', [rfReplaceAll]);
         STR146 := StringReplace(STR145, 'Ǘx', 'Ǘ’', [rfReplaceAll]);
         STR147 := StringReplace(STR146, 'Ttch', 'Tch', [rfReplaceAll]);
         Writeln('');
         Writeln('Brazilian orthography:');
         Writeln('');
         TextColor(15);
         Writeln('   ',STR147);
   { TIKUNA: COLOMBIA }
         STR1 := INPUT3;
         STR2 := StringReplace(STR1, 'j', 'y', [rfReplaceAll]);
         STR3 := StringReplace(STR2, 'J', 'Y', [rfReplaceAll]);
         STR4 := StringReplace(STR3, 'tch', 'ch', [rfReplaceAll]);
         STR5 := StringReplace(STR4, 'Tch', 'Ch', [rfReplaceAll]);
         STR6 := StringReplace(STR5, 'TCH', 'CH', [rfReplaceAll]);
         STR7 := StringReplace(STR6, 'nh', 'ñ', [rfReplaceAll]);
         STR8 := StringReplace(STR7, 'Nh', 'Ñ', [rfReplaceAll]);
         STR9 := StringReplace(STR8, 'NH', 'Ñ', [rfReplaceAll]);
         STR10 := StringReplace(STR9, 'c', 'k', [rfReplaceAll]);
         STR11 := StringReplace(STR10, 'C', 'K', [rfReplaceAll]);
         STR12 := StringReplace(STR11, 'kh', 'ch', [rfReplaceAll]);
         STR13 := StringReplace(STR12, 'Kh', 'Ch', [rfReplaceAll]);
         STR14 := StringReplace(STR13, 'KH', 'CH', [rfReplaceAll]);
         STR15 := StringReplace(STR14, 'qui', 'ki', [rfReplaceAll]);
         STR16 := StringReplace(STR15, 'Qui', 'Ki', [rfReplaceAll]);
         STR17 := StringReplace(STR16, 'QUI', 'KI', [rfReplaceAll]);
         STR18 := StringReplace(STR17, 'que', 'ke', [rfReplaceAll]);
         STR19 := StringReplace(STR18, 'Que', 'Ke', [rfReplaceAll]);
         STR20 := StringReplace(STR19, 'QUE', 'KE', [rfReplaceAll]);
         STR21 := StringReplace(STR20, 'q', 'k', [rfReplaceAll]);
         STR22 := StringReplace(STR21, 'Q', 'K', [rfReplaceAll]);
         STR23 := StringReplace(STR22, 'x', '', [rfReplaceAll]);
         STR24 := StringReplace(STR23, 'X', '', [rfReplaceAll]);
         STR25 := StringReplace(STR24, '''', '', [rfReplaceAll]);
         STR26 := StringReplace(STR25, '’', '', [rfReplaceAll]);
         Writeln('');
         TextColor(7);
         Writeln('Colombian orthography:');
         Writeln('');
         TextColor(15);
         Writeln('   ',STR26);
   { TIKUNA: ILV }
         STR1 := INPUT3;
         STR2 := StringReplace(STR1, 'j', 'y', [rfReplaceAll]);
         STR3 := StringReplace(STR2, 'J', 'Y', [rfReplaceAll]);
         STR4 := StringReplace(STR3, 'tch', 'ch', [rfReplaceAll]);
         STR5 := StringReplace(STR4, 'Tch', 'Ch', [rfReplaceAll]);
         STR6 := StringReplace(STR5, 'TCH', 'CH', [rfReplaceAll]);
         STR7 := StringReplace(STR6, 'nh', 'ñ', [rfReplaceAll]);
         STR8 := StringReplace(STR7, 'Nh', 'Ñ', [rfReplaceAll]);
         STR9 := StringReplace(STR8, 'NH', 'Ñ', [rfReplaceAll]);
         STR10 := StringReplace(STR9, 'q', 'c', [rfReplaceAll]);
         STR11 := StringReplace(STR10, 'Q', 'C', [rfReplaceAll]);
         STR12 := StringReplace(STR11, 'à', 'a', [rfReplaceAll]);
         STR13 := StringReplace(STR12, 'ò', 'o', [rfReplaceAll]);
         STR14 := StringReplace(STR13, 'è', 'e', [rfReplaceAll]);
         STR15 := StringReplace(STR14, 'ì', 'i', [rfReplaceAll]);
         STR16 := StringReplace(STR15, 'ù', 'u', [rfReplaceAll]);
         STR17 := StringReplace(STR16, 'ǜ', 'ü', [rfReplaceAll]);
         STR18 := StringReplace(STR17, 'À', 'A', [rfReplaceAll]);
         STR19 := StringReplace(STR18, 'Ò', 'O', [rfReplaceAll]);
         STR20 := StringReplace(STR19, 'È', 'E', [rfReplaceAll]);
         STR21 := StringReplace(STR20, 'Ì', 'I', [rfReplaceAll]);
         STR22 := StringReplace(STR21, 'Ù', 'U', [rfReplaceAll]);
         STR23 := StringReplace(STR22, 'Ǜ', 'Ü', [rfReplaceAll]);
         STR24 := StringReplace(STR23, 'ki', 'qui', [rfReplaceAll]);
         STR25 := StringReplace(STR24, 'Ki', 'Qui', [rfReplaceAll]);
         STR26 := StringReplace(STR25, 'KI', 'QUI', [rfReplaceAll]);
         STR27 := StringReplace(STR26, 'ke', 'que', [rfReplaceAll]);
         STR28 := StringReplace(STR27, 'Ke', 'Que', [rfReplaceAll]);
         STR29 := StringReplace(STR28, 'KE', 'QUE', [rfReplaceAll]);
         STR30 := StringReplace(STR29, 'kí', 'quí', [rfReplaceAll]);
         STR31 := StringReplace(STR30, 'Kí', 'Quí', [rfReplaceAll]);
         STR32 := StringReplace(STR31, 'KÍ', 'QUÍ', [rfReplaceAll]);
         STR33 := StringReplace(STR32, 'ké', 'qué', [rfReplaceAll]);
         STR34 := StringReplace(STR33, 'Ké', 'Qué', [rfReplaceAll]);
         STR35 := StringReplace(STR34, 'KÉ', 'QUÉ', [rfReplaceAll]);
         STR36 := StringReplace(STR35, 'k', 'c', [rfReplaceAll]);
         STR37 := StringReplace(STR36, 'K', 'C', [rfReplaceAll]);
         STR38 := StringReplace(STR37, 'a''', 'ax', [rfReplaceAll]);
         STR39 := StringReplace(STR38, 'ã''', 'ãx', [rfReplaceAll]);
         STR40 := StringReplace(STR39, 'a̱''', 'a̱x', [rfReplaceAll]);
         STR41 := StringReplace(STR40, 'ã̱''', 'ã̱x', [rfReplaceAll]);
         STR42 := StringReplace(STR41, 'á''', 'áx', [rfReplaceAll]);
         STR43 := StringReplace(STR42, 'e''', 'ex', [rfReplaceAll]);
         STR44 := StringReplace(STR43, 'ẽ''', 'ẽx', [rfReplaceAll]);
         STR45 := StringReplace(STR44, 'e̱''', 'e̱x', [rfReplaceAll]);
         STR46 := StringReplace(STR45, 'ẽ̱''', 'ẽ̱x', [rfReplaceAll]);
         STR47 := StringReplace(STR46, 'é''', 'éx', [rfReplaceAll]);
         STR48 := StringReplace(STR47, 'i''', 'ix', [rfReplaceAll]);
         STR49 := StringReplace(STR48, 'ĩ''', 'ĩx', [rfReplaceAll]);
         STR50 := StringReplace(STR49, 'i̱''', 'i̱x', [rfReplaceAll]);
         STR51 := StringReplace(STR50, 'ĩ̱''', 'ĩ̱x', [rfReplaceAll]);
         STR52 := StringReplace(STR51, 'í''', 'íx', [rfReplaceAll]);
         STR53 := StringReplace(STR52, 'o''', 'ox', [rfReplaceAll]);
         STR54 := StringReplace(STR53, 'õ''', 'õx', [rfReplaceAll]);
         STR55 := StringReplace(STR54, 'o̱''', 'o̱x', [rfReplaceAll]);
         STR56 := StringReplace(STR55, 'õ̱''', 'õ̱x', [rfReplaceAll]);
         STR57 := StringReplace(STR56, 'ó''', 'óx', [rfReplaceAll]);
         STR58 := StringReplace(STR57, 'u''', 'ux', [rfReplaceAll]);
         STR59 := StringReplace(STR58, 'ũ''', 'ũx', [rfReplaceAll]);
         STR60 := StringReplace(STR59, 'u̱''', 'u̱x', [rfReplaceAll]);
         STR61 := StringReplace(STR60, 'ũ̱''', 'ũ̱x', [rfReplaceAll]);
         STR62 := StringReplace(STR61, 'ú''', 'úx', [rfReplaceAll]);
         STR63 := StringReplace(STR62, 'ü''', 'üx', [rfReplaceAll]);
         STR64 := StringReplace(STR63, 'ü̃''', 'ü̃x', [rfReplaceAll]);
         STR65 := StringReplace(STR64, 'ü̱''', 'ü̱x', [rfReplaceAll]);
         STR66 := StringReplace(STR65, 'ü̱̃''', 'ü̱̃x', [rfReplaceAll]);
         STR67 := StringReplace(STR66, 'ǘ''', 'ǘx', [rfReplaceAll]);
         STR68 := StringReplace(STR67, '''', 'X', [rfReplaceAll]);
         STR69 := StringReplace(STR68, 'a’', 'ax', [rfReplaceAll]);
         STR70 := StringReplace(STR69, 'ã’', 'ãx', [rfReplaceAll]);
         STR71 := StringReplace(STR70, 'a̱’', 'a̱x', [rfReplaceAll]);
         STR72 := StringReplace(STR71, 'ã̱’', 'ã̱x', [rfReplaceAll]);
         STR73 := StringReplace(STR72, 'á’', 'áx', [rfReplaceAll]);
         STR74 := StringReplace(STR73, 'e’', 'ex', [rfReplaceAll]);
         STR75 := StringReplace(STR74, 'ẽ’', 'ẽx', [rfReplaceAll]);
         STR76 := StringReplace(STR75, 'e̱’', 'e̱x', [rfReplaceAll]);
         STR77 := StringReplace(STR76, 'ẽ̱’', 'ẽ̱x', [rfReplaceAll]);
         STR78 := StringReplace(STR77, 'é’', 'éx', [rfReplaceAll]);
         STR79 := StringReplace(STR78, 'i’', 'ix', [rfReplaceAll]);
         STR80 := StringReplace(STR79, 'ĩ’', 'ĩx', [rfReplaceAll]);
         STR81 := StringReplace(STR80, 'i̱’', 'i̱x', [rfReplaceAll]);
         STR82 := StringReplace(STR81, 'ĩ̱’', 'ĩ̱x', [rfReplaceAll]);
         STR83 := StringReplace(STR82, 'í’', 'íx', [rfReplaceAll]);
         STR84 := StringReplace(STR83, 'o’', 'ox', [rfReplaceAll]);
         STR85 := StringReplace(STR84, 'õ’', 'õx', [rfReplaceAll]);
         STR86 := StringReplace(STR85, 'o̱’', 'o̱x', [rfReplaceAll]);
         STR87 := StringReplace(STR86, 'õ̱’', 'õ̱x', [rfReplaceAll]);
         STR88 := StringReplace(STR87, 'ó’', 'óx', [rfReplaceAll]);
         STR89 := StringReplace(STR88, 'u’', 'ux', [rfReplaceAll]);
         STR90 := StringReplace(STR89, 'ũ’', 'ũx', [rfReplaceAll]);
         STR91 := StringReplace(STR90, 'u̱’', 'u̱x', [rfReplaceAll]);
         STR92 := StringReplace(STR91, 'ũ̱’', 'ũ̱x', [rfReplaceAll]);
         STR93 := StringReplace(STR92, 'ú’', 'úx', [rfReplaceAll]);
         STR94 := StringReplace(STR93, 'ü’', 'üx', [rfReplaceAll]);
         STR95 := StringReplace(STR94, 'ü̃’', 'ü̃x', [rfReplaceAll]);
         STR96 := StringReplace(STR95, 'ü̱’', 'ü̱x', [rfReplaceAll]);
         STR97 := StringReplace(STR96, 'ü̱̃’', 'ü̱̃x', [rfReplaceAll]);
         STR98 := StringReplace(STR97, 'ǘ’', 'ǘx', [rfReplaceAll]);
         STR99 := StringReplace(STR98, '’', 'X', [rfReplaceAll]);
         Writeln('');
         TextColor(7);
         Writeln('Peruvian orthography (ILV):');
         Writeln('');
         TextColor(15);
         Writeln('   ',STR99);
   { TIKUNA: FORMABIAP }
         STR1 := INPUT3;
         STR2 := StringReplace(STR1, 'j', 'y', [rfReplaceAll]);
         STR3 := StringReplace(STR2, 'J', 'Y', [rfReplaceAll]);
         STR4 := StringReplace(STR3, 'tch', 'ch', [rfReplaceAll]);
         STR5 := StringReplace(STR4, 'Tch', 'Ch', [rfReplaceAll]);
         STR6 := StringReplace(STR5, 'TCH', 'CH', [rfReplaceAll]);
         STR7 := StringReplace(STR6, 'nh', 'ñ', [rfReplaceAll]);
         STR8 := StringReplace(STR7, 'Nh', 'Ñ', [rfReplaceAll]);
         STR9 := StringReplace(STR8, 'NH', 'Ñ', [rfReplaceAll]);
         STR10 := StringReplace(STR9, 'à', 'a', [rfReplaceAll]);
         STR11 := StringReplace(STR10, 'ò', 'o', [rfReplaceAll]);
         STR12 := StringReplace(STR11, 'è', 'e', [rfReplaceAll]);
         STR13 := StringReplace(STR12, 'ì', 'i', [rfReplaceAll]);
         STR14 := StringReplace(STR13, 'ù', 'u', [rfReplaceAll]);
         STR15 := StringReplace(STR14, 'ǜ', 'ü', [rfReplaceAll]);
         STR16 := StringReplace(STR15, 'À', 'A', [rfReplaceAll]);
         STR17 := StringReplace(STR16, 'Ò', 'O', [rfReplaceAll]);
         STR18 := StringReplace(STR17, 'È', 'E', [rfReplaceAll]);
         STR19 := StringReplace(STR18, 'Ì', 'I', [rfReplaceAll]);
         STR20 := StringReplace(STR19, 'Ù', 'U', [rfReplaceAll]);
         STR21 := StringReplace(STR20, 'Ǜ', 'Ü', [rfReplaceAll]);
         STR22 := StringReplace(STR21, 'á', 'a', [rfReplaceAll]);
         STR23 := StringReplace(STR22, 'ó', 'o', [rfReplaceAll]);
         STR24 := StringReplace(STR23, 'é', 'e', [rfReplaceAll]);
         STR25 := StringReplace(STR24, 'í', 'i', [rfReplaceAll]);
         STR26 := StringReplace(STR25, 'ú', 'u', [rfReplaceAll]);
         STR27 := StringReplace(STR26, 'ǘ', 'ü', [rfReplaceAll]);
         STR28 := StringReplace(STR27, 'Á', 'A', [rfReplaceAll]);
         STR29 := StringReplace(STR28, 'É', 'E', [rfReplaceAll]);
         STR30 := StringReplace(STR29, 'Í', 'I', [rfReplaceAll]);
         STR31 := StringReplace(STR30, 'Ó', 'O', [rfReplaceAll]);
         STR32 := StringReplace(STR31, 'Ú', 'U', [rfReplaceAll]);
         STR33 := StringReplace(STR32, 'Ǘ', 'Ü', [rfReplaceAll]);
         STR34 := StringReplace(STR33, 'c', 'k', [rfReplaceAll]);
         STR35 := StringReplace(STR34, 'C', 'K', [rfReplaceAll]);
         STR36 := StringReplace(STR35, 'kh', 'ch', [rfReplaceAll]);
         STR37 := StringReplace(STR36, 'Kh', 'Ch', [rfReplaceAll]);
         STR38 := StringReplace(STR37, 'KH', 'CH', [rfReplaceAll]);
         STR39 := StringReplace(STR38, 'qui', 'ki', [rfReplaceAll]);
         STR40 := StringReplace(STR39, 'Qui', 'Ki', [rfReplaceAll]);
         STR41 := StringReplace(STR40, 'QUI', 'KI', [rfReplaceAll]);
         STR42 := StringReplace(STR41, 'que', 'ke', [rfReplaceAll]);
         STR43 := StringReplace(STR42, 'Que', 'Ke', [rfReplaceAll]);
         STR44 := StringReplace(STR43, 'QUE', 'KE', [rfReplaceAll]);
         STR45 := StringReplace(STR44, 'q', 'k', [rfReplaceAll]);
         STR46 := StringReplace(STR45, 'Q', 'K', [rfReplaceAll]);
         STR47 := StringReplace(STR46, 'a''', 'ax', [rfReplaceAll]);
         STR48 := StringReplace(STR47, 'ã''', 'ãx', [rfReplaceAll]);
         STR49 := StringReplace(STR48, 'a̱''', 'ax', [rfReplaceAll]);
         STR50 := StringReplace(STR49, 'ã̱''', 'ãx', [rfReplaceAll]);
         STR51 := StringReplace(STR50, 'e''', 'ex', [rfReplaceAll]);
         STR52 := StringReplace(STR51, 'ẽ''', 'ẽx', [rfReplaceAll]);
         STR53 := StringReplace(STR52, 'e̱''', 'ex', [rfReplaceAll]);
         STR54 := StringReplace(STR53, 'ẽ̱''', 'ẽx', [rfReplaceAll]);
         STR55 := StringReplace(STR54, 'i''', 'ix', [rfReplaceAll]);
         STR56 := StringReplace(STR55, 'ĩ''', 'ĩx', [rfReplaceAll]);
         STR57 := StringReplace(STR56, 'i̱''', 'ix', [rfReplaceAll]);
         STR58 := StringReplace(STR57, 'ĩ̱''', 'ĩx', [rfReplaceAll]);
         STR59 := StringReplace(STR58, 'o''', 'ox', [rfReplaceAll]);
         STR60 := StringReplace(STR59, 'õ''', 'õx', [rfReplaceAll]);
         STR61 := StringReplace(STR60, 'o̱''', 'ox', [rfReplaceAll]);
         STR62 := StringReplace(STR61, 'õ̱''', 'õx', [rfReplaceAll]);
         STR63 := StringReplace(STR62, 'u''', 'ux', [rfReplaceAll]);
         STR64 := StringReplace(STR63, 'ũ''', 'ũx', [rfReplaceAll]);
         STR65 := StringReplace(STR64, 'u̱''', 'ux', [rfReplaceAll]);
         STR66 := StringReplace(STR65, 'ũ̱''', 'ũx', [rfReplaceAll]);
         STR67 := StringReplace(STR66, 'ü''', 'üx', [rfReplaceAll]);
         STR68 := StringReplace(STR67, 'ü̃''', 'ü̃x', [rfReplaceAll]);
         STR69 := StringReplace(STR68, 'ü̱''', 'üx', [rfReplaceAll]);
         STR70 := StringReplace(STR69, 'ü̱̃''', 'ü̃x', [rfReplaceAll]);
         STR71 := StringReplace(STR70, 'A̱', 'A', [rfReplaceAll]);
         STR72 := StringReplace(STR71, 'Ã̱', 'Ã', [rfReplaceAll]);
         STR73 := StringReplace(STR72, 'E̱', 'E', [rfReplaceAll]);
         STR74 := StringReplace(STR73, 'Ẽ̱', 'Ẽ', [rfReplaceAll]);
         STR75 := StringReplace(STR74, 'I̱', 'I', [rfReplaceAll]);
         STR76 := StringReplace(STR75, 'Ĩ̱', 'Ĩ', [rfReplaceAll]);
         STR77 := StringReplace(STR76, 'O̱', 'O', [rfReplaceAll]);
         STR78 := StringReplace(STR77, 'Õ̱', 'Õ', [rfReplaceAll]);
         STR79 := StringReplace(STR78, 'U̱', 'U', [rfReplaceAll]);
         STR80 := StringReplace(STR79, 'Ũ̱', 'Ũ', [rfReplaceAll]);
         STR81 := StringReplace(STR80, 'Ü̱', 'Ü', [rfReplaceAll]);
         STR82 := StringReplace(STR81, 'Ü̱̃', 'Ü̃', [rfReplaceAll]);
         STR83 := StringReplace(STR82, '''', 'X', [rfReplaceAll]);
         STR84 := StringReplace(STR83, 'a’', 'ax', [rfReplaceAll]);
         STR85 := StringReplace(STR84, 'ã’', 'ãx', [rfReplaceAll]);
         STR86 := StringReplace(STR85, 'a̱’', 'ax', [rfReplaceAll]);
         STR87 := StringReplace(STR86, 'ã̱’', 'ãx', [rfReplaceAll]);
         STR88 := StringReplace(STR87, 'e’', 'ex', [rfReplaceAll]);
         STR89 := StringReplace(STR88, 'ẽ’', 'ẽx', [rfReplaceAll]);
         STR90 := StringReplace(STR89, 'e̱’', 'ex', [rfReplaceAll]);
         STR91 := StringReplace(STR90, 'ẽ̱’', 'ẽx', [rfReplaceAll]);
         STR92 := StringReplace(STR91, 'i’', 'ix', [rfReplaceAll]);
         STR93 := StringReplace(STR92, 'ĩ’', 'ĩx', [rfReplaceAll]);
         STR94 := StringReplace(STR93, 'i̱’', 'ix', [rfReplaceAll]);
         STR95 := StringReplace(STR94, 'ĩ̱’', 'ĩx', [rfReplaceAll]);
         STR96 := StringReplace(STR95, 'o’', 'ox', [rfReplaceAll]);
         STR97 := StringReplace(STR96, 'õ’', 'õx', [rfReplaceAll]);
         STR98 := StringReplace(STR97, 'o̱’', 'ox', [rfReplaceAll]);
         STR99 := StringReplace(STR98, 'õ̱’', 'õx', [rfReplaceAll]);
         STR100 := StringReplace(STR99, 'u’', 'ux', [rfReplaceAll]);
         STR101 := StringReplace(STR100, 'ũ’', 'ũx', [rfReplaceAll]);
         STR102 := StringReplace(STR101, 'u̱’', 'ux', [rfReplaceAll]);
         STR103 := StringReplace(STR102, 'ũ̱’', 'ũx', [rfReplaceAll]);
         STR104 := StringReplace(STR103, 'ü’', 'üx', [rfReplaceAll]);
         STR105 := StringReplace(STR104, 'ü̃’', 'ü̃x', [rfReplaceAll]);
         STR106 := StringReplace(STR105, 'ü̱’', 'üx', [rfReplaceAll]);
         STR107 := StringReplace(STR106, 'ü̱̃’', 'ü̃x', [rfReplaceAll]);
         STR108 := StringReplace(STR107, '’', 'X', [rfReplaceAll]);
         Writeln('');
         TextColor(7);
         Writeln('Peruvian orthography (FORMABIAP):');
         Writeln('');
         TextColor(15);
         Writeln('   ',STR108);
         TextColor(7);
         Writeln('');
         Halt;
      End;

   End;

   { INCORRECT FIRST PARAMETER }

Begin
   TextColor(4);
   Writeln('Error:    Invalid parameters provided!');
   Writeln('');
   GoTo HELP;
End;

End.
